### ISSUE TITLE
Opens in enormous window by default

### ISSUE THREAD

**Issue by axfelix** [libretro/beetle-psx-libretro#105]
This plugin defaults to opening a window much larger than my desktop and I have to resize it manually every time. Is there any fix for this?

**Comment by fr500** [comment]
set window scale to something smaller, it's 3x framebuffer size by default

**Comment by axfelix** [comment]
it's possible I don't understand how that setting is supposed to work globally -- if I set window scale to something lower than 3x in the main config menu before loading a core, the text is illegible, but "3x" to the psx hw plugin seems to mean about 4000px horizontal, and trying to change it from within the game crashes the core.

**Comment by cascardian** [comment]
A bit late, but I'll try to explain: The problem is that the internal resolution scaling of the core interacts with the global window scaling. It's how it works. I agree that it's a bit unintuitive to have these settings coupled like that. If you want to work around this and keep using higher internal resolutions, you need to set a separate window scaling for the core. I have it set up so the Beetle PSX HW core launches with a video_scale of 1, while RA by itself uses 4 (all with integer scaling). That works for 2x internal resolution on  a 1080p monitor to keep the window size consistent.

Don't worry, though, @fr500 is aware of it and opened an issue for RA: https://github.com/libretro/RetroArch/issues/3749

**Comment by rz5** [comment]
@axfelix - is this still happening?

**Comment by axfelix** [comment]
Nope, this was fixed at some point in the past few months.

**Comment by rz5** [comment]
Great, thanks for chiming in.
