### ISSUE TITLE
Backport GPU cache emulation

### ISSUE THREAD

**Issue by Oggom** [libretro/beetle-psx-libretro#12]
Beetle PSX libretro is currently missing GPU cache emulation which was added in Mednafen 0.9.37-UNSTABLE,

It is needed to render the heat engine effects in various Formula One games correctly and prevents flickering on the map screen of Tactics Ogre.

**Comment by Oggom** [comment]
Rewrote this issue for clarity.

**Comment by Nine-H** [comment]
I don't want to make a duplicate bug, is this the reason why framebuffer effects don't work in opengl?
![psx metal gear solid-170721-023257](https://user-images.githubusercontent.com/20123543/28449941-68ceec94-6e27-11e7-84d6-d76b19a65d27.png)

**Comment by hizzlekizzle** [comment]
No, that's a different issue.

**Comment by DarkSwan86** [comment]
Crash Team Racing (E) [SCES-02105] seems affected: when you use the time freeze powerup the entire screen is filled with white textures from the GUI. 
![problem](https://user-images.githubusercontent.com/24975273/29639550-5e1a4e30-885b-11e7-89c4-9acc057ee79a.png)

Manjaro Linux - Retroarch 1.6.3 - Mesa 17.1.6 on SandyBridge graphic (Intel HD) - PSX HW core from 8/23 buildbot.

**Comment by OptimalJew** [comment]
I wonder if what DarkSwan86 is experiencing is a different issue altogether, as the 'Time Stop' power-up in CTR is giving me what appears to be the intended 'shifting blur' effect (using the most recent build of Beetle PSX ). Meanwhile, the pre-race engine effect in F1 2000 is broken as expected, and displaying what I can best describe as flickering transparent squares that are unfortunately very difficult to capture with still images.

![ctr - crash team racing usa -170904-090506](https://user-images.githubusercontent.com/31424143/30027761-49ccd2ba-9150-11e7-888e-b1fcb328f150.png)

**Comment by rz5** [comment]
@DarkSwan86, see the post above...check if you're both using the same renderer (software, presumably).

If any of you know of a better test case for the GPU cache emulation other than the heat effect from the pre-race section in the F1 2000 game, do post it here please. Ideally something that doesn't last only 1 frame or happens once in the entirety of the game.

**Comment by DarkSwan86** [comment]
@rz5 I've retested both software mode and OpenGL:

-On software mode all the effects are correct (Missiles heat, Time effect and Warp powerup)
-On OpenGL i still have the white outline when i use the time effect and both the missiles heat and warp powerup effects are messed up, it's hard to show on the screenshot below:
![missile](https://user-images.githubusercontent.com/24975273/30061223-d8c7a002-9246-11e7-82a8-26d61f8e28df.png)
![warp](https://user-images.githubusercontent.com/24975273/30061224-d8cba7f6-9246-11e7-9945-fb6ea9132dd2.png)

I've updated my Manjaro installation with the latest Mesa (17.1.8) and both Retroarch (1.6.7) and latest buildbot version of both Software and Hardware PSX Beetle (09/04/2017 build)

@OptimalJew Are you sure that you are using the HW accellerated version of beetle? What are your PC specs and OS? Thank you!

**Comment by OptimalJew** [comment]
@DarkSwan86 Was using Beetle PSX (non-HW) with SW rendering (1050 ti/3570k/win7 64). Using Beetle PSX HW I had the following results with the 'Time Stop' power-up.: 

**Open GL**
![ctr - crash team racing usa -170905-104843](https://user-images.githubusercontent.com/31424143/30067183-1b764f08-9228-11e7-9569-3cacf99e7001.png)
**Vulkan**
![ctr - crash team racing usa -170905-104918](https://user-images.githubusercontent.com/31424143/30067192-20217cd0-9228-11e7-871c-d120d877bbe0.png)
**Software**
![ctr - crash team racing usa -170905-104946](https://user-images.githubusercontent.com/31424143/30067207-27d640b4-9228-11e7-9105-9939e2c04914.png)

Could this problem with CTR in particular be an issue with HW rendering, and not the aforementioned lack of GPU Cache emulation?

**Comment by rz5** [comment]
@DarkSwan86 I assume you know that to use the vulkan renderer, you need the vulkan video driver selected on RetroArch and do a restart.

In your pictures, it seems like 'Vulkan' and 'OpenGL' are both just the GL renderer.
That type of effect seems like it's mask bit related rather than GPU cache emulation related. And Vulkan implements mask bit emulation

**Comment by OptimalJew** [comment]
@rz5 I had no idea you had to swap the renderer in RA as well. Looks like you're right, both SW and Vulkan work as intended.

**Vulkan**
![ctr - crash team racing usa -170905-113333](https://user-images.githubusercontent.com/31424143/30069238-33f61f3a-922e-11e7-8bd9-3c7a57214952.png)

**Comment by DarkSwan86** [comment]
@rz5 Sandybridge doesn't support Vulkan at all (on intel only from Broadwell and up on Linux) so i can check only the Software and OpenGL render. With the test from @OptimalJew i think we can say that the bug lies within the OpenGL render, (different GPUs, different drivers, different OS, same error on the same OpenGL render can't be a coincidence). Do you need additional data to help debugging? Thanks!

**Comment by simias** [comment]
I think I got it to work, at least it doesn't seem to break any game I've tried and the "haze" effect in F1 2000 looks improved, although I don't know what it's supposed to look like on real hardware:

![f1 2000 usa -171008-124803](https://user-images.githubusercontent.com/7925386/31316126-31f3f136-ac27-11e7-8283-2d9644d6dfea.png)

Note that increasing the internal resolution changes the way these types of effects behave since the size of the cache remains the same. Maybe we could increase the size of the cache proportionally with the IR scaling factor but frankly I'm not sure if it's worth it.

**Comment by Oggom** [comment]
I've tested F1 Championship Season 2000, Formula One 2001 and Tactics Ogre and they all appear to work as intended now. Thank you very much!

**Comment by simias** [comment]
Cool, thank you for testing.
