### ISSUE TITLE
problem with reading some eboot/pbp files

### ISSUE THREAD

**Issue by bigboo3000** [libretro/beetle-psx-libretro#130]
Hi
beetle psx can't read some games converted in eboot (there is only a black screen when loading the game).

I tested with "Need for Speed, The - Road & Track Presents" (USA):
run the redump verified .cue .bin >ok
convert the .bin to .PBP with PSX2PSPv1.4.2 > beetle psx can't run the  game (but the pbp works fine in other psx emulators)

The same apply with the following games:
Gran Turismo 2 (USA)
FIFA99 (USA)
NBA live 99 (USA)
Need for speed 3 (USA)
NHL98 (USA)
Wipe out 2097 (EU)
Wipe out 3 se (EU) (the game menu load, but it can't start a race)

**Comment by saftle** [comment]
Are you using the mednafen psx or the mednafen psx hw core? Also if you're using "hw" are you using the GL or Vulkan core?

**Comment by bigboo3000** [comment]
hw with vulkan renderer

**Comment by saftle** [comment]
could you perhaps try with the GL renderer to double check? I had no problems loading any PBP with the GL renderer not too long ago. You'll need to change your driver version to GL as well or else Mednafen psx hw will continue to use vulkan.

**Comment by bigboo3000** [comment]
I just tested with mednafen software renderer and it's the same.
Only the games I listed are not working in .pbp format, all others .pbp are working fine.

**Comment by saftle** [comment]
Oh ok interesting. When I have a little time I'll try and convert those same games to PBP to see if my results vary.

**Comment by bigboo3000** [comment]
Thanks!

**Comment by saftle** [comment]
Yeah, I was able to reproduce this with "NBA Live 99 (USA)" that was converted from a verified redump dump, so it looks like it is definitely an issue with specific games.

**Comment by Zapeth** [comment]
I made a little adjustment in the code which should hopefully resolve this issue -> https://github.com/Zapeth/beetle-psx-libretro

However I can't say for certain if there are possible conflicts with other games due to this change so feel free to try out as many games as you can (not only the ones that weren't working before).

The change should only have an effect during the boot process (or when switching discs), so make sure to check for any changes there (possibly slightly longer/shorter loading times than previously, possibly a short flickering screen that wasn't there before or games that won't boot at all).

**Comment by bigboo3000** [comment]
Thank you for this quick bugfix.
Can you push this to libretro main repository so I can test it?

**Comment by Zapeth** [comment]
Actually I found a conflicting game, so I'd like to hold off any pushing upstream until thats resolved as well.

**Comment by Zapeth** [comment]
Hmm, this might actually be a more complicated issue overall.

First off, I actually wrote the code initially with these changes that I just made, but this lead to other games not booting up -> https://github.com/libretro/beetle-psx-libretro/issues/36#issuecomment-218378584

Second, the entire issue seems to be that track start offsets in some converted PBP files are slightly incorrect, specifying the start of a track either one or two frames too soon or too late (happens mostly for discs with pregaps).

However I don't really know why this is a mednafen-specific problem, or rather why other emulators don't seem to have this issue.
My current guess is that other emulators are more lenient than mednafen in processing this information but it could of course also be something in my implementation that I'm not seeing or doing wrong.

Either way, I'm not sure how to proceed from here, maybe somebody with more insight in this matter (PSX disc reading) can explain why these games won't boot in mednafen with slightly incorrect start offsets (or why they do boot in other emulators)?

**Comment by bigboo3000** [comment]
If this tool psx2psp 1.42 was messing up data during conversion the resulting pbp should be altered no?

But if you convert back this pbp to iso with the same tool, the resulting iso have a crc32 matching the original one, so there is nothing altered.

(I tested this on need for speed 3 iso/pbp)

**Comment by Zapeth** [comment]
No, the raw data (.bin file) isn't modified at all during conversion (just compressed), thats why you get the same hash as the original after re-converting it.

The problematic part lies within the TOC data (.cue file if you have one) which specifies the starting points of the tracks in the image.

Now for simple one-track PSX discs this data is moreless always the same, thats why you are able to run most images using just the .bin file.
However this data becomes essential when dealing with multi-track discs and/or disc images that feature a pre/post gap, because there isn't really a way to figure out this extra information solely from the raw data -> https://en.wikipedia.org/wiki/Cue_sheet_(computing)#Cue_sheet_syntax

Apparently psx2psp 1.42 implicitly loads the .cue file if you have one in the same folder as the selected .bin file and parses them incorrectly (mostly for multi-track discs but also any tracks that have pregaps), resulting in the aforementioned small offsets which mednafen doesn't seem to like all that much for some games.

**Comment by bigboo3000** [comment]
Thanks I understand better.
But if we take need for speed 3, the TOC seems very simple (no multitrack, no pregap), yet this game doesn't work

FILE "Need for Speed III - Hot Pursuit (USA).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

**Comment by Zapeth** [comment]
Yes, thats why I'm guessing the changed code here is the way it should normally work.

I could issue a pull request now but I'm not sure how many converted games that will affect in a negative way (compared to how many are affected now).

Personally I would first like figure out why mednafen seems to be more strict with these offsets than other emulators and then possibly try to implement a similar behavior (even though it is a dirty solution).

An ideal solution would be to fix the core issue, namely the conversion tool that writes the wrong offsets but that won't be easy/quick since the one thats commonly used isn't open source.
I actually have been working on one myself based on a different conversion tool (which is a lot more bare-bones than psx2psp 1.42 but at least open source) but its still far from being ready for a release.

**Comment by daninthemix** [comment]
Any progress on this? I'm facing the same issue with:

Wipeout (US)
Wipeout XL (US)

**Comment by Zapeth** [comment]
I kind of put it on hold after my last comment but looked into it again today and I think I found a workaround that shouldn't require a reconversion of the images (see pull request)

I know it doesn't fix the core issue but considering how established the conversion tool probably is I'm not sure its even worth trying (not to mention that most people don't seem to care/notice any wrong audio offsets anyway).

Anyway it would be great if somebody could do some testing to verify if this works as intended or not, starting with these games:

Gran Turismo 2 (USA)
FIFA99 (USA)
NBA live 99 (USA)
Need for speed 3 (USA)
NHL98 (USA)
Wipe out 2097 (EU)
Wipe out 3 se (EU)
Wipeout (US)
Wipeout XL (US)
Resident Evil - Director's Cut - Dual Shock Edition
Resident Evil 2 - Dual Shock Edition
Tales of Destiny II (Tales of Eternia)
Chrono Cross

If someone stumbles upon a game that has issues (not booting or crashing) make sure to also try the original bin/cue files afterwards to ensure the problem isn't elsewhere.

**Comment by daninthemix** [comment]
I just tested the following and they all work fine:

Wipeout (USA)
Wipeout XL (USA)
Resident Evil - Director's Cut (USA)
Resident Evil 2 - Dual Shock (USA)
Tales of Destiny 2 (USA)
Need for Speed 3 (USA)
Chrono Cross (USA)

So it seems like this is fixed! All we need now are savestates working on mutidisc PBPs!

**Comment by CecilFF4** [comment]
My Wipeout XL (USA) does not work: it hangs on the second loading screen. I've tested it with cue/bin/pbp. It's a verified good copy as it was ripped straight from one of my personal discs and the image works in other emulators. My setup is as follows:

Retroarch 1.5.0
Tried both Beetle PSX HW 0.9.44.1 76862ab  AND  Beetle PSX 0.9.44.1 76862ab
Tried with all video drivers available.

On the other hand, my Chrono Cross (USA) seems to work just fine, but I don't care about that because it was a crappy game. :P

**Comment by Zapeth** [comment]
Which loading screen are you exactly referring to? I got ingame without any problems using the latest commit (https://github.com/libretro/beetle-psx-libretro/commit/76862abefdde9097561e2b795e75b49247deff17) of the HW core with a pbp converted by PSX2PSP.

Though as seen by the various games that stopped booting, mednafen (or at least the libretro core versions) seems to be kind of finicky with some games in regards to slight offsets of the tracks.

What's the SHA-1 checksum of your ripped image (bin file) and what's listed in your cue sheet?

**Comment by CecilFF4** [comment]
There are two loading screens you come upon before you get to the menu (the blue background with the word "Loading" in WOXL font); the second one hangs. I've left it on that screen for many minutes and it never got to the menu.

My bin's SHA-1 is: 78CFBCE88B6F00746B3AD33234B54415C4545983
CUE:
FILE "Wipeout XL.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

Also, I used PSX2PSP to convert to PBP as well, but I tried all 3 file types. Hopefully the SHA is fine, but I can re-rip if needed.

**Comment by Zapeth** [comment]
To clarify, loading your cue/bin files worked or not? Because if not then this is not a pbp issue and the wrong place for this discussion.

Also, your cue sheet only lists the data track, the other eleven audio tracks are missing which indicates an incorrect/incomplete dump and is probably what causes your issue in the first place (since I could replicate the issue by removing the audio track entries in my cue sheet).

**Comment by CecilFF4** [comment]
My apologies, then, that this may have been posted in the wrong section. It was all 3 files types that were having the same issue. I'm not sure how I lost the audio tracks, but I appreciate you telling me of their absence. Again, sorry for posting in the wrong place.
