### ISSUE TITLE
No speedup with vulkan

### ISSUE THREAD

**Issue by JacobAL** [libretro/beetle-psx-libretro#138]
There doesn't seem to be any way to increase speed (turn off frame rate throttling) if the Vulkan renderer is being used. This may be due to vsync being on, but this does not cause issues with OGL with vsync on.

**Comment by hizzlekizzle** [comment]
Correct. That's a known bug: you can't disable vsync with Vulkan.

**Comment by JacobAL** [comment]
I suppose it's a problem with the whole of retroarch really, not just beetle.

**Comment by twinaphex** [comment]
Honestly, I'd pin the blame more on your GPU vendor's drivers rather than anything else.

I can disable vsync on Linux with an Intel iGPU. I think people are too quick to blame RetroArch when it comes to Vulkan-related issues. Vulkan is still a relatively young API and not a lot of vendors are implementing everything in a bug-free manner.

On nVidia you have the usual reluctance to not give the 'user' (in this case - read developer) full access over buffering / swap chain modes, due to what I presume to be legacy reasons and various parts of their GPU ecosystem relying on buffering mode being configured by the driver instead. It's very, very hard to get them off this mentality, and I presume it's just a big culture clash where they presume their driver knows better than the actual user application. On Intel iGPU you get less resistance when it comes to the user application being able to configure swapchains exactly how you'd like it, swapchain set to 1 is single buffering there and not double buffering, etc because of 'reasons'.

I don't know what the situation is like on AMD, there might be similar issues there. Overall, though, I think most of the issues are not our fault but simply stubborn GPU vendors insisting on a certain way which just massively limits your options from an application perspective.

**Comment by JacobAL** [comment]
Fair enough, thanks for the info. I do indeed have an nvidia card.

**Comment by rz5** [comment]
JacobAL: I also have Nvidia on my PC and I think my problems are like yours.

In my case, pressing spacebar to fast forward while using paraLLEl/beetle-psx's vk renderer does not work.
I know of a workaround that sometimes works, it's as follows:
- Press spacebar (according to the log, this also turns off Vsync);
- Toggle fullscreen/windowed;
- Observe the core getting fast-forwarded.

Could you please try my workaround a couple of times and report back?

**Comment by JacobAL** [comment]
Thanks, but this doesn't seem to work for me.

**Comment by ThePagel** [comment]
You need to do one of two things with nvidia drivers.

Exit out of full screen, click on the window tab and enable exclusive full screen mode.
Or
Open retroarch go to windowed mode if not already and right click on desktop and select nvidia control panel. click on "manage 3d settings" then the "program" tab and find retroarch (might need to add). Adjust the following then click apply:
Power manaement: prefer max performance
Threaded optimization: off
Triple buffering: off
Vsync: 3d application setting

You should now have FF working, sometimes it still wont work for me, If it never works it is more likely you're taxing your system to the point ff is not possible. Does anyone know if there is a way we could launch exclusive Full screen via command prompt in window? Because that works for me every time.

**Comment by hizzlekizzle** [comment]
I think this is fixed on the latest nightlies. Could you please test and verify?

**Comment by ThePagel** [comment]
I'll try it out when I get home if nobody beats me to it.

**Comment by ThePagel** [comment]
still not working as it should for me

**Comment by Awakened0** [comment]
The Windows buildbot has been down since before the fix, so the last nightly on it doesn't have it. I got a build from a dev in #retroarch to test it out. It does work, but there is a black screen flicker when you first enable FF and everything gets wavy in motion.

**Comment by saftle** [comment]
This should be fixed now, and the vulkan flicker issue has been documented here: https://github.com/libretro/RetroArch/issues/3268. I think we can close this issue.

**Comment by rz5** [comment]
Alright, then this is closed as it's an invalid report; it is (was) a frontend bug, not a core bug.
