### ISSUE TITLE
Save-states overwrite memory card data

### ISSUE THREAD

**Issue by JacobAL** [libretro/beetle-psx-libretro#175]
I recently noted that upon loading a saved state, the memory card will show what was saved at that state, rather than what the last save to the memory card was. This is annoying, as usually I like to drop a save state in slot 0 at the title screen to get to the load game screen as fast as possible.

This has only been a problem recently. I've noticed it since I started using the vulkan renderer, when that strange 1/4 screen glitch started with OGL. I've tried my older core (from before vulkan was fully implemented) and the issue still occurs there (even though it was never an issue before).
I think that this may be a problem with retroarch, rather than a problem with the mednafen-beetle core. I am not sure whether this issue affects any other cores.

**Comment by hizzlekizzle** [comment]
There's a setting to disable this behavior: settings > saving > don't overwrite saveram when loading savestate.

**Comment by JacobAL** [comment]
Thanks man. Other users had been reporting it as an issue so i assumed it was a bug, guess we were just being dumb.

**Comment by mick-p1982** [comment]
Excuse me, this is insane (https://github.com/ShendoXT/memcardrex/issues/9) ... a memory card is not a game state.

**Comment by cgarz** [comment]
Ah this explains alot! VERY counter intuitive for the PSX. Memcards and save states really should be separate. At least for the PSX. @mick-p1982's off topic [comment](https://github.com/libretro/RetroArch/issues/7198#issuecomment-441430494) is more succinct than I could be.

@JacobAL perhaps this issue should be changed to a feature request to change the default for beetle cores?

**Comment by faospark** [comment]
Im sorry for basically necroposting on this but i just noticed something
The default setting of retroarch seems to be to have this turned OFF but the setting in itself is a NEGATIVE.
Which means you are actually allowing to overwrite the SaveRam 

This can lead to catastrophic  loss of game progress. someone can mistake load the save state via short cut key and not realize they have lost everything . 
![Screenshot_8](https://user-images.githubusercontent.com/11664809/197374806-f193fd56-30bd-4da5-9422-34aaf05b6fb8.png)

Possible solution is to either turn the option to ON by the default or rephase the setting so that it is not a negative
