### ISSUE TITLE
No controller response on Ape Escape PAL

### ISSUE THREAD

**Issue by RaydenX93** [libretro/beetle-psx-libretro#220]
When I get to the main menu of Ape Escape PAL (Redump version), I can't move around the menu or select any option. The controller looks like it isn't connected. I'm using a Dualshock 4 connected via Bluetooth, correctly recognised by RA and working on every other game, analog sticks included. The "DualShock" mode is selected in "Controls" (if I don't choose that the game tells me to connect a dualshock controller so I think the controller is correctly seen by the game). I tried changing the option "DualShock Analog button toggle" ON and OFF but nothing happens, pressed L1 + L2 + R1+ R2 + Start + Select and in both modes nothing happens.

Is there anything else I can try or is this a problem with the code?

Thanks

RetroArch 1.6.7 2ff6bee
Beetle PSX HW 0.9944.1 20924c5

**Comment by rz5** [comment]
@RaydenX93 If you have any remap files, you could try deleting them. I also had an issue with Ape Escape, but that was because the core was setting my controller type to 'PS1 Joypad' or 'None'.

**Comment by RaydenX93** [comment]
@rz5 I don't have any remap files plus, as I said, i set the controller to "Dualshock"

**Comment by TheOligopolist** [comment]
I believe the problem is caused the copy protection the PAL version uses. The image you are using likely doesn't have the sub channel data available.

Grab all the downloads from the games redump page here:
http://redump.org/disc/6147/

Put them all in the same folder as your disc image and make sure they are all named exactly the same (don't change the file extensions though.)

That should get the game to work correctly.

**Comment by RaydenX93** [comment]
It worked! Thanks! I had no idea this could be a issue. Maybe it should be written somewhere for posterity?

**Comment by rz5** [comment]
I'll consider adding that to the README.md of the repo.
