### ISSUE TITLE
Playstation .sbi files with PBP or even multidisc PBP

### ISSUE THREAD

**Issue by parasven** [libretro/beetle-psx-libretro#241]
Using SBI files with PBP Images does not seem to work. 

I will just quote my own post from over at libretro forums:

> Does anyone have experience with Playstation game in pbp format + sbi (Subchanneldata) files? Some games need the because they are copyprotected. Im using the core: https://github.com/libretro/beetle-psx-libretro
> 
> Using the sbi files with normal .cue/bin images does indeed work just fine.
> 
> Using the same sbi file with pbp does not work, although there seems to be code to load sbi files when using pbp files see: https://github.com/libretro/beetle-psx-libretro/blob/6cfd34ab307d08d5bcde543a95cdcd00f54afec0/mednafen/cdrom-new/CDAccess_PBP.cpp
> 
> One line in that sourcecode even mentions multidisc pbp sbi support:
> 
> `// for multi-disc images change the sbi file syntax to [filename]_[disc_number].sbi instead of [filename].sbi if(PBP_DiscCount > 1) { // use a substitute char here, set the proper one in Read_TOC() sbi_path.insert(sbi_path.length()-4, “_x”); }`
> 
> Using the Syntax described in that comment did not work for me though. Or i am actually doing something wrong here.

Link to the forum Thread: https://forums.libretro.com/t/beetle-psx-playstation-sbi-files-with-pbp-or-even-multidisc-pbp/12759

**Comment by DukeJP** [comment]
Some .sbi related: with parasite eve 2, pal version with sbi file, Is impossible to change disc. Just freezes in "change disc" screen. By fortune, i discovered you can actually save at the end of the story in disc one (Douglas Cabin) just before you take the car to the mines, and load this data in disc 2. With this, no disc swap is needed. 
No other multidisc game have this problem, and PE2 is the only multidisc with pbi files i have.

**Comment by parasven** [comment]
Some more testing:

**Final Fantasy 9 Pal German single disc BIN/CUE:**
Files: 
- Final Fantasy IX (G) (Disc 1) [SLES-02967].bin
- Final Fantasy IX (G) (Disc 1) [SLES-02967].cue
- Final Fantasy IX (G) (Disc 1) [SLES-02967].sbi

Result: No Blackscreen and booting the game just fine.

[singledisc BIN and CUE.log](https://github.com/libretro/beetle-psx-libretro/files/1391950/singledisc.BIN.and.CUE.log)



**Final Fantasy 9 Pal German single disc PBP:**
Files: 
- Final Fantasy IX (G) (Disc 1) [SLES-02967].PBP
- Final Fantasy IX (G) (Disc 1) [SLES-02967].sbi

Result: Blackscreen and game does not boot

[singledisc PBP.log](https://github.com/libretro/beetle-psx-libretro/files/1391956/singledisc.PBP.log)



**Final Fantasy 9 Pal German multidisc PBP:**
Files: 
- Final Fantasy IX [PAL-G] (SLES-02967).PBP
- Final Fantasy IX [PAL-G] (SLES-02967)_1.sbi
- Final Fantasy IX [PAL-G] (SLES-02967)_2.sbi
- Final Fantasy IX [PAL-G] (SLES-02967)_3.sbi
- Final Fantasy IX [PAL-G] (SLES-02967)_4.sbi

Result: Blackscreen and game does not boot

[multidisc PBP.log](https://github.com/libretro/beetle-psx-libretro/files/1391965/multidisc.PBP.log)

**Comment by rz5** [comment]
@Zapeth - You might be interested in this thread.

**Comment by Zapeth** [comment]
Hmm a quick glance at the source code makes me suspect that I forgot to change the sbi data when switching discs, that would explain why multi-disc images won't load after switching (probably the effects of the protection).

If I'm right a fix should be easy, just need to find the time to do it (since I'd also like to test it myself if possible).

As for @parasven 's issues with FF9, I just tried it myself and it booted without issues into the main menu. However looking at your logs it looks like you're on a *nix system so the file extension name might be the issue here (tested on Windows on my end).

It's not really clear in the code but the way the image gets loaded it checks whether the image extension name is upper or lower case and then assumes that to be the same case for the sbi file extension name (which is somewhat annoying due to psx2pbp always storing the image name in upper case).

Generally it should [show in the log whenever an sbi file gets loaded/used](https://github.com/libretro/beetle-psx-libretro/blob/815febac035be00ca9070a9b4069bbc54e5563e1/mednafen/cdrom/CDAccess_PBP.cpp#L709), though I guess since the log message is set at `RETRO_LOG_DEBUG` level it won't show up by default and you'll need to set the log verbosity to include debug messages for the time being.

**Comment by parasven** [comment]
@Zapeth  Thanks you for the valuable hint with the file extensions, that was indeed the problem. 
I can confirm that that both the singledisc PBP and multidisc PBPs now boot without any problem.

Maybe, when you find the time, you could include a fix for that upper/lowercase problem. More people will probably stumble over this and have problem. In the meantime im gonna spread the word about it in other forums.

When looking at the collection of sbi files i downloaded from redump.org they are about 88Kb in size.
Wouldnt it be possible to just include the whole collection right into the core or would that clutter it too much? This would make the games just work like any other non protected game. 

Just some thoughts here and if it is a stupid idea just dismiss it.

**Comment by Zapeth** [comment]
Actually nevermind my last statement about not changing the sbi data when swapping discs in multi-disc PBP files.
This should already happen in the current code, assuming the file name casing is exactly the same as the disc image file (with an added _x postfix to the name where x stands for the disc number).

As for the name casing "issue" itself, its actually implemented the same way for other file types in the core, so changing it only here would break consistency.
Plus, this method is actually the most consistent way you can do it (without having to check every possible name casing variation), I mean you could force it to only accept lower case but there might be people that prefer having their files entirely in upper case and this would be a problem for them.

As for your suggestion regarding including the sbi files in the core, I don't think it would be a good idea to do it.
It would certainly be possible, but then you'd also need to set up some kind of game database to be able to identify whenever an sbi file needs to be loaded and that in itself is a can of worms you don't want to open.

The proper way to deal with the sbi data would be to either
- include it in the file format somehow and have the core load it from there (very inconvenient in case of PBP files since the most popular/used converter is closed source and considering the format itself is proprietary as well it would only be a hacked solution)
- or get rid of the copy protection entirely (unfortunately I don't know enough about CD formats and the copy protection itself to be able to say if thats even feasible and considering the current situation works well enough I don't really want to spend my time on it either)

Anyway, unless someone here is still not able to load/switch a PBP disc that uses libcrypt I'd say this issue can be closed again.

PS: I will probably make a PR for the sbi relevant log messages though, just for easier troubleshooting.

**Comment by Rafuten** [comment]
Hi! @parasven 
In other forum i read this: 

> Final Fantasy 9 Pal German single disc PBP:
> Files:
> 
>     Final Fantasy IX (G) (Disc 1) [SLES-02967].PBP
>     Final Fantasy IX (G) (Disc 1) [SLES-02967].sbi
> 
> Result: Blackscreen and game does not boot

The problem is in extension .PBP .sbi, the extension they have same letters .PBP .SBI | .pbp .sbi

sorry for mi english, i hope you have understood me ;)

Regards!
