### ISSUE TITLE
Absolute Paths in M3U Files don't work

### ISSUE THREAD

**Issue by kencinder** [libretro/beetle-psx-libretro#254]
Using absolute paths in M3U files winds up with the emulator trying to load the path to the M3U files with the path in the M3U files tacked onto the end, resulting in an incorrect path.

ie; Loading `X:\path\to\m3u\game.m3u` results in Retroarch trying to load `X:\path\to\m3u\X:\path\to\game.disc.cue`, either from the command line or the GUI.

I tried using the same M3Us in standalone Mednafen, and they work perfectly fine.

**Comment by fr500** [comment]
that's good imho, absolute paths on such a thing are the devil's work 
:p

**Comment by kencinder** [comment]
Absolute paths are necessary when your sets are not all dumped into the same folder for 1 game, and as a result you can't put an M3U in with all the disc images in one folder.

**Comment by hizzlekizzle** [comment]
I don't see how that necessitates absolute paths. Can you give an example?

**Comment by kencinder** [comment]
I don't see how not having them work is an issue, closing.

**Comment by fr500** [comment]
I guess he wants to have all m3us in one dir an point to another dir with the cue+bins or something.

**Comment by kencinder** [comment]
Yes, I have a folder outside my Disc Image path for M3U, to keep them out of my set. I use a batch to create them, and it includes the full path, resolving only a relative path is not accurate with respect to discs in individual folders.
I didn't see why such a thing as using absolute paths would be an issue, but it appears it is, so I closed.

**Comment by simias** [comment]
Sounds like a pretty easy fix to be honest. Don't concatenate the base dir if the path in the CUE is absolute. On most systems you can just test `if (path[0] == '/')` but of course that won't work on Windows because that would be too simple. Apparently the Windows API has a function for that: https://msdn.microsoft.com/en-us/library/bb773660%28v=vs.85%29.aspx

There's also `is_absolute` in the standard C++ filesystem library but that's C++17: http://en.cppreference.com/w/cpp/filesystem

Or maybe on windows one could just check `if (path[1] == ':')`, I'm sure it's not 100% correct but probably good enough for most cases.
