### ISSUE TITLE
PGXP - Perspective corrected textures - Untextured polygons with solid/graded colors bug

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#257]
This issue was best described by @rz5 
> When using the 'Perspective corrected textures' option, untextured polygons with solid/graded colors will incorrectly get rendered with some sort of camera-angle-based noise added.

This is a duplicate of https://github.com/libretro/beetle-psx-libretro/issues/85#issuecomment-265540682, https://github.com/libretro/beetle-psx-libretro/issues/85#issuecomment-266030079, and https://github.com/libretro/beetle-psx-libretro/issues/85#issuecomment-267790659 in order to create a bounty issue.

--------

A few screenshots from the aforementioned linked issue:

**Tenchu**

Option Disabled: https://cloud.githubusercontent.com/assets/8117159/20982318/db8f3b32-bcaf-11e6-898a-b7694cfac5b1.png
Option Enabled: https://cloud.githubusercontent.com/assets/8117159/20982332/f2892c26-bcaf-11e6-8f24-75f9fe5ede7c.png

**Metal Gear Solid**

Option Disabled: https://cloud.githubusercontent.com/assets/8117159/21290109/6e36bc00-c4a6-11e6-8bc1-1b400aa5557e.png
Option Enabled: https://cloud.githubusercontent.com/assets/8117159/21290110/6e3a2570-c4a6-11e6-9da6-2d5638df08c8.png

More screenshots can be found here: https://github.com/libretro/beetle-psx-libretro/issues/85

--------

Let's start this one off with a bounty of $20.

In order to claim this bounty, the bug must be fixed in software, GL, and Vulkan (if there is even a difference in the implementation in this case).

**Bountysource Thread**: https://www.bountysource.com/issues/51334773-pgxp-perspective-corrected-textures-untextured-polygons-with-solid-graded-colors-bug

**Comment by kenshen112** [comment]
note these error's seem to be GL specific.

**Comment by saftle** [comment]
The error also happens when using the vulkan renderer/driver. Or did you mean something else @kenshen112 ?

**Comment by simias** [comment]
I'm guessing the problem is related to the interpolated fragment color messing up in certain situations when PGXP is enabled. One way to confirm that would be to edit the fragment shader code:

https://github.com/libretro/beetle-psx-libretro/blob/7616e0125984bc07deb6a0526c30c3cac7e4e388/rsx/shaders_gl/command_fragment.glsl.h#L28

Add the "noperspective" specifier to disable interpolation, if it fixes the "noise" then it's probably a good hint that that's the problem. Maybe it's worth testing with "flat" to disable interpolation altogether to make debugging easier and make sure it's completely unrelated to interpolation. See https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Interpolation_qualifiers

If that's really the problem then there may be a saturation issue somewhere but I'm not really sure.

**Comment by saftle** [comment]
Interestingly enough, it appears to affect only Nvidia cards, according to a few users on Reddit (https://www.reddit.com/r/emulation/comments/7bq1z0/a_long_lasting_pgxp_perspective_corrected/) with AMD cards.

**Comment by kenshen112** [comment]
I'm on intel and am getting the same issues, and sorry for my earlier comment i meant that for another thread.

**Comment by simias** [comment]
Can somebody upload a savestate for Tenchu? Seems like a good test case but I'm not sure how complicated it is to reproduce.

**Comment by iCatButler** [comment]
I finally managed to get my hands on an Nvidia card and take a look at this (my apologies for the delay).

It looks like the noise is some sort of rounding error in the `frag_texture_coord` value. It only appears to affect texture lookups which are 0 dimension on one or both axes. It appears that in Tomb Raider Lara's skin is coloured by a single point texture lookup and in MGS Snake's sleeve is a 1D strip that's stretched.

A quick solution that seems to work is adding a half pixel offset to the `coords` at beginning of the `sample_texel()` function. Basically:
```
coords.x += 0.5 / 1025;
coords.y += 0.5 / 512;
```
I haven't seen any errors created by doing this, though I've not tested it extensively. I'd upload the change but it's relatively minor and I had to make some pretty big hacks to get things compiling in MSVC.

**Comment by fr500** [comment]
Thanks for looking into this

If you ever want to setup the toolchain we use
https://buildbot.libretro.com/docs/compilation/windows/

**Comment by saftle** [comment]
Thanks for looking into this guys. I can't wait to try it out!

**Comment by saftle** [comment]
I went ahead and added the lines manually and compiled locally. It fixes the problem with the GL renderer on Metal Gear Solid at the beginning! Awesome stuff.

However, I noticed that the Vulkan renderer still has the problem. The software renderer appears to not be afflicted with the bug.

**Comment by twinaphex** [comment]
@iCatButler We'd be more than happy to merge your changes to get it working on MSVC.

**Comment by twinaphex** [comment]
So far, those changes have certainly fixed the issues in Tekken 3 and other games where I saw the graphical anomalies.

There are still some PGXP perspective correction glitches elsewhere though, however, they have been there before this patch too, so I will start posting Youtube videos on them separately in hopes @iCatButler  may be able to figure out what the problem is.

As for these two-line changes, I assume it won't have any regressions when perspective correction is disabled altogether? I'll just push the commit for now since it didn't seem to have any adverse effects so far based on my testing.

@saftle Vulkan still has the issue because it has a completely different renderer and different shaders, so the same fix would have to be applied for its renderer. And it relies on glslc to convert it to SPIRV bytecode. I might be able to backport it.

**Comment by saftle** [comment]
@twinaphex Sounds promising. I'm excited to do some in-depth testing once you find the necessary changes.

**Comment by twinaphex** [comment]
Hi there @iCatButler ,

I made a video of some long-standing bugs with perspective correction - excuse the horrible sound -

https://www.youtube.com/watch?v=biO3KtNEmT0&feature=youtu.be

https://www.youtube.com/watch?v=dDl4b9okw_s&feature=youtu.be

https://www.youtube.com/watch?v=eq1Qn_shn4Q&feature=youtu.be

**Comment by saftle** [comment]
@twinaphex I managed to reproduce all three of your errors on the GL renderer, but all three are not reproducible with the Vulkan renderer. I hope this helps isolate the problem further.

**Comment by saftle** [comment]
The bounty is now at $55. I am really excited to see the commit (https://github.com/libretro/beetle-psx-libretro/commit/535daf75266392f4db22c5748478c42c2e67c519) that got fixed in the GL renderer get ported to the Vulkan renderer as well!

**Comment by saftle** [comment]
I can confirm that https://github.com/libretro/beetle-psx-libretro/pull/312 fixed this issue on Vulkan. Thank you @iCatButler !

**Comment by twinaphex** [comment]
Hi there @iCatButler, 

would you like to claim this bounty?

https://www.bountysource.com/issues/51334773-pgxp-perspective-corrected-textures-untextured-polygons-with-solid-graded-colors-bug

There is $55 attached to this Github issue, so that could be all yours if you want it.

**Comment by iCatButler** [comment]
Hi @twinaphex,

I wouldn't feel comfortable accepting money for this, but thanks for the offer. The fixes were relatively simple in the end, it's really just circumstances that meant it took so long to resolve.

If it's of use to you, while I initially tried to get the core compiling with MSVC there is a significant amount of preprocessor code related to shader loading that doesn't appear to be compatible. The Vulkan implementation in particular uses a GCC specific feature to directly include the pre-compiled shaders as string literals.

The OpenGL renderer instead had an issue with the order in which MSVC evaluated preprocessor commands, stringifying the content of the shader before parsing it, so none of the embedded preprocessor branches to do with texture filtering were resolved. The glsl compiler then failed at runtime when it hit those lines (commenting them out allowed it to run without filtering).
It might be possible to hint to the preprocessor the order of evaluation or enable preprocessing for the glsl compiler, rather than relying on the C preprocessor to handle it while compiling.

I didn't investigate the solutions too far though in case any modifications made it harder for the original authors to maintain their code.

**Comment by twinaphex** [comment]
> I didn't investigate the solutions too far though in case any modifications made it harder for the original authors to maintain their code.

That shouldn't be an issue though, this repository is the upstream for that code, it isn't used anywhere else.

**Comment by backgamon** [comment]
On my RTX 2070 i have that issue with some filters xBR, SABR and 3-Point.
Others filters doesn't have this.
https://github.com/libretro/beetle-psx-libretro/issues/527
