### ISSUE TITLE
CD Access Method "PreCache" crashes when pbp is over 2 GB in size

### ISSUE THREAD

**Issue by Gibdos** [libretro/beetle-psx-libretro#293]
When trying to start a multi-disc PBP that is over 2GB in size, RetroArch will crash, when the CD Access Method **PreCache** is used. With **Sync** or **ASync** it works fine.

Since I have 16GB RAM, it shouldn't be a problem of available RAM.
Easiest way to reproduce it is with FF VIII NTSC-U, since I cannot get the size below 2GB, even with highest pbp compression.

**Comment by hizzlekizzle** [comment]
Are you using a 32-bit build? I believe 2GB is the most RAM a 32-bit application can access.

**Comment by Gibdos** [comment]
No, I used the 64bit RetroArch Installer. So I am assuming that RetroArch is running with 64bit.

**Comment by remyabel** [comment]
@hizzlekizzle It's actually 3 GB. And there's always the LAA.

@Gibdos What platform? What tool? I'm on Linux and used PSX2PSP to convert SLUS00892 from 4 *.bin's to a 2.8GB PBP. I do not get a crash. Can you also provide any information about the crash? Error messages, logs, etc.

**Comment by retro-wertz** [comment]
Im not claiming that i know whats going on or i know how to fix but i just did basic routine of tracing, and looks like this is where the crash is when opening PBP files of at least 2GB size:

https://github.com/libretro/beetle-psx-libretro/blob/master/mednafen/MemoryStream.cpp#L39
the size seems to be -1 here, but im not sure how "size" should be calculated because the same game can load successfully with caching disabled (set to sync or async) and that still returns -1 for size while loading smaller than 1GB PBP are returning actualy files sized in bytes.

Rom tested FFVIII
PBP Size : 2,212,574,811 bytes

**Comment by rz5** [comment]
@Gibdos, could you please confirm the fix and close the issue aftwards?

**Comment by Gibdos** [comment]
Just grabbed the latest retroarch nightly 2018-02-15 and updated the Beetle PSX HW and Beetle PSX cores and my 2GB FF VIII pbp works without problems when set to PreCache now. Thanks alot for the fix 👍
