### ISSUE TITLE
Retropie ROMs not launching

### ISSUE THREAD

**Issue by EldritchIHC** [libretro/beetle-psx-libretro#316]
I am using retropie on ubuntu.
I installed lr-beetle-psx for retopie through the pacakge manager.I loaded Medievil(without placing any bios in the bios folder) and it worked very well,before that i have tried lr-psxrearmed and it lagged a bit.
I dont know why it doesnt work anymore,i get a black screen with a white bar and then it gets me back tot the selection screen.I tried reinstalling lr-beetle,changing the roms ,changing resolution,messing with bios files and nothing.

**Comment by hizzlekizzle** [comment]
I think you were probably mistaken that it worked without a BIOS before. Beetle-psx definitely needs BIOS images is very particular about which BIOS images it needs. 85%+ of the problems people have launching games with this core are related to BIOS and another ~10% are related to bad ROMs/dumps/cue sheets.

If you need more help, the libretro forums are a better place for this sort of thing, as github is for reporting bugs rather than tech support.
