### ISSUE TITLE
In newest Nightly build there is only hardware and software option for rendering ?

### ISSUE THREAD

**Issue by Kristijan1001** [libretro/beetle-psx-libretro#325]
What happen to OpenGL, Vulcan etc ? Why are they all gone ?

It used to be like this, i think this was downloaded last week ?

![](https://i.imgur.com/uPowvVw.png)

Core Version:

![](https://i.imgur.com/sTjLdpE.png)

**Comment by SpaceAgeHero** [comment]
Rendering method is (and always was...) inherited from selected video driver in Retroarch settings.

**Comment by Kristijan1001** [comment]
@SpaceAgeHero hmm ok , just wanna say littarlly a week ago it had Vulcan, OpenGL, etc to select in core options , but i guess thats fine too :)

**Comment by rz5** [comment]
Before the last couple of commits, users could select between 'software', 'opengl' and 'vulkan' renderers and the core would be smart enough to fallback to some other renderer if the user didn't pick the corresponding frontend video driver.

However, the same mistake kept being made by several users and bug reports kept getting submitted that pertained to the GL renderer instead of the vk renderer and vice-versa

This can be considered bad design on the core's part, so now it just exposes 'software' and 'hardware'. The latter option will simply make the core try to pick a matching renderer to the frontend's video driver.

**Comment by Kristijan1001** [comment]
@rz5 you are right thanks alot !
