### ISSUE TITLE
 [OpenGL] Azure Dreams - Sprites are distorted

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#347]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760GTX

Description: The sprites in Azure Dreams (PAL) are distorted. All sprites are jumping around and are crashed during gameplay.

Screenshots:
![azure dreams-180624-205915](https://user-images.githubusercontent.com/10263536/41822892-034a133c-77f7-11e8-93bb-dd50992f4713.png)
![azure dreams-180624-205854](https://user-images.githubusercontent.com/10263536/41822894-0721cca2-77f7-11e8-889d-a576d8252f67.png)

**Comment by saftle** [comment]
Instead of me replying to all of your threads, I figured I'd only reply to one of them. The reason for most of the problems that you're seeing is most likely due to you having Software Framebuffer "Off". This needs to be on, and should never be turned off. It was meant as a peformance hack, but it causes graphical issues.

**Comment by Papermanzero** [comment]
Then the option should be deleted :-(

**Comment by saftle** [comment]
Also, when testing/creating bug reports, PGXP should be disabled. Most games work with  PGXP operation mode: Memory only, PGXP vertex cache: Off, and PGXP perspective correct texturing: On, however some games don't like any of the PGXP options. They should only be enabled on a game by game basis.

By default, Frame Buffer is on, and the PGXP options are off. I recommend going back to the defaults, or else you won't know if an optional feature is the culprit.

**Comment by Papermanzero** [comment]
Framebuffer is on. Issue is still visible. Also the other issues are not related to the Framebuffer. Did a check and every game had the same issue.

PGXP shall NOT affect sprites. As stated in one on my descriptions, PCSX-PGXP displays all games correct. That means, the implementation of PSX Libretro is not correct, which leads to bugs.

**Comment by twinaphex** [comment]
Take it up with @iCatButler , he made both implementations (in PCSXR and beetle).

**Comment by iCatButler** [comment]
The characters in Azure Dreams aren't being rendered as sprites, they're just 2D polygons, which is why PGXP is influencing them.

Again this seems to be the Vertex Cache at fault. It really shouldn't be enabled unless you absolutely need it, and its easy enough to tell that's the problem just be toggling it off. That said, it seems a lot more broken than I'd expect, even with stale values in the cache.

**Comment by anothername99** [comment]
Not sure if this is the time for game-specific reports. They're early in development and pretty much everything is broken at this point.

**Comment by Papermanzero** [comment]
Proposal would be to disable the pgxp vertex cache and software framebuffer in the retroarch menu. For debugging and development reasons the options should be available in the config file, but for the end user it is more confusing (especially in term of pgxp if the behaviour is different compared to pcxr)

**Comment by saftle** [comment]
@Papermanzero PGXP IS disabled by default and the software framebuffer IS enabled by default. If you hadn't enabled optional game dependent features, then you wouldn't have had these issues.

So they aren't bugs. What you're proposing IS already like that by default. @iCatButler is the person behind the PGXP feature and has told you explicitly that Vertex Cache should be off when it comes to this game.

Please close all of your PGXP related issues (and other optional features like OGL filtering, where it also only works on certain games) rather than wasting the developer's valuable time. Most likely a game DB of some kind is the only solution to providing game dependent fixes.

**Comment by Papermanzero** [comment]
I mean, hide it :-)

**Comment by saftle** [comment]
@Papermanzero This is the state of the feature. Please look at https://www.libretro.com/index.php/mednafenbeetle-psx-pgxp-arrives/ under **How to use it?** for more information, since you obviously weren't aware.

**Comment by saftle** [comment]
It appears @iCatButler may have committed something that affects this in https://github.com/libretro/beetle-psx-libretro/commit/eb6bbfbced0069db989e39f827775b6002cb6cf6. I'm not sure, so maybe the state of the feature has changed.

**Comment by iCatButler** [comment]
That change disables perspective correction on primitives that use the cache. It means the extreme levels of distortion reported here won't happen.

@Papermanzero ideally the vertex cache should be removed from both emulators. It's an implementation of edgbla's original GTE accuracy hack, I called it vertex caching to try and better describe how it works but it's probably causing more confusion about what it's for.

If you're using it in combination with PGXP (whether memory only or CPU mode) the vertex cache almost certainly won't produce positions that haven't already been passed through correctly anyway. What it does is allow the system to find the nearest value to any untreated vertices, snapping them together and closing up holes in meshes. These positions are almost certainly wrong, but the error is less noticeable than gaps.

The PCSX-R implementation takes advantage of the way chain DMAs are processed all at once by the GPU plugin to assign a lifetime to values in the cache. That reduces the number of hits overall, meaning you'll get fewer errors on objects that were never processed by the GTE (mostly 2D) but you might get worse coverage on 3D elements (not that it's correct behaviour anyway).

That's why I suggest leaving it off on either emulator unless you see glaring holes in meshes without it, at best it will do nothing at all and at worst it will still cause added distortion on untreated elements.

**Comment by saftle** [comment]
@iCatButler does the change affect both the GL and Vulkan renderers?

**Comment by iCatButler** [comment]
@saftle it should do. The change happens before the vertices are fed into the API specific renderers.

**Comment by Papermanzero** [comment]
Fixed with commit a8aa726
