### ISSUE TITLE
[OpenGL] Castlevania Symphonia of the Night - Sprite Tiles and Distorted Sprites

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#350]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: With bilinear filter, Castlevania (PAL) has a tile effect (lines between sprites). With other filtering methods this is not appearing. Also PCSX1 with PGXP (standalone version) does not have this effect, with bilinear activated. Moreover some sprites like the candles are distorted. They are shaking left and right.

Screenshot (Tile effect):
![castlevania - symphony of the night-180624-210233](https://user-images.githubusercontent.com/10263536/41822973-4d9ce904-77f8-11e8-905a-4945fd93867d.png)

Screenshot (Distorted Sprites - See Candle):
![castlevania - symphony of the night-180624-210301](https://user-images.githubusercontent.com/10263536/41822976-590b4e70-77f8-11e8-8c4d-26869fb6bf0e.png)

**Comment by rz5** [comment]
The distortion is most likely PGXP perspective correction related and that feature isn't really needed in a mostly 2D game.

The tiling effect bug is most likely caused by the 'texture filtering' core option being set to bilinear.

**Comment by Papermanzero** [comment]
Yes indeed. PGXP has to be optimised for PSX Libretro (the same games are working fine with standalone PCSX-PGXP and PGXP enabled). 
Concerning bilinear filtering: Using another filtering method resolves the issue. However normally bilinear filtering should also work without limitations.

**Comment by twinaphex** [comment]
I think any changes to PGXP are best left to @iCatButler as he naturally knows best how the code should work.

PGXP is an enhancement feature though, this is not a general GL renderer problem. You can play with PGXP turned off in the meantime if it bothers you that much.

**Comment by iCatButler** [comment]
This doesn't seem to be related to PGXP. I thought it might have been caused by the half texel offset applied to fix Nvidia cards, but it persists even when that is reverted. PGXP doesn't really work for this game in general as the 3D elements tend to require some CPU input.

I think all of the bilinear texture filtering errors seen on sprites are due to a lack of clamping at the edges of textures, meaning they blend in colours from outside the desired area. Pete's GPU plugins, which the PCSX-R implementation relies on, process all textures into RGB format tiles before they are used and set fixed function clamping of UVs to the edges to prevent this.

It might be possible to update the bilinear filtering methods to clamp samples manually to the edges of the desired texture region (if those are known at the time of sampling).

**Comment by iCatButler** [comment]
@twinaphex I think I've got solutions to both these problems now.

Looking over Pete's code it's not quite a simple as I thought, he seems to be generating texture atlases with entries based on actual draw commands. The area of texture used by the primitive is sampled, colour lookups performed and then written as a rectangle into the atlas with the outer edge pixels duplicated as a border for bilinear lookups.

By passing the min and max UV coordinates as uniform vertex data for each primitive I can effectively recreate that border by simply clamping any texture lookups within that area. It means that there will be a hard border between adjoining primitives but in practice it looks okay (at least on Crash). I'll do some more testing to make sure it works for the other games that are flagged.

The vertex cache can be mostly fixed by disabling perspective correction for any primitives that use it. That should remove the worst of the distortion. For removing stale values I'd need a point of reference to know when the GTE has finished transforming one batch of vertices. An operation that only occurs at the start/end of a frame on the CPU side might do, do you know of anything like that?
Even with stale values the cache should be _better_ with just the perspective correction disabled.

**Comment by twinaphex** [comment]
Hey @iCatButler , awesome to hear about this!

As for these entry points for when the GTE has finished transforming batches of vertices, I will have to take a peek into the codebase and see if I can pinpoint something. I will also try inviting @simias to the discussion since he would be best placed to know where we could find that in the codebase.

**Comment by iCatButler** [comment]
This is the same scene with bilinear filtering and texture samples clamped:
![castlevania - symphony of the night usa -180701-145117](https://user-images.githubusercontent.com/17948959/42135992-8e062f02-7d4b-11e8-95ba-54ef05cc45f5.png)

There are a few more before/after examples for bilinear filtering and the other options here: https://imgur.com/a/a0NX8M7

**Comment by Papermanzero** [comment]
Fixed with commit  a8aa726
