### ISSUE TITLE
[OpenGL/Vulkan/Upscaled Software] Soul Blade/Edge - Water does not render correctly

### ISSUE THREAD

**Issue by saftle** [libretro/beetle-psx-libretro#385]
Original reported by @twinaphex here: https://github.com/libretro/beetle-psx-libretro/issues/43#issuecomment-220839628

> Both software rendering at higher than 1x resolution and the GL rendering produce the same graphics errors here. Only 1x software mode renders the water correctly. Top is GL, middle is software renderer at 4x, and bottom is the software renderer at 1x.
> 
> https://cloud.githubusercontent.com/assets/1075274/15454927/e5a59762-2045-11e6-9dcf-710af002807d.png
> 
> https://cloud.githubusercontent.com/assets/1075274/15454928/e5a6abe8-2045-11e6-8763-96ed56cd7105.png
> 
> https://cloud.githubusercontent.com/assets/1075274/15454929/e5a731bc-2045-11e6-963e-375a9911deda.png

I was also able to confirm all of what @twinaphex posted against the newest commit using default settings: 581a08fc62a21515e4f9d9fb2d0e96e5da434f43

The problem exists also when using the Vulkan renderer, and not just the GL renderer, or the software renderer when upscaled.

I have also attached a save state for easy debugging: 
[soul blade (usa) (v1.1).state.zip](https://github.com/libretro/beetle-psx-libretro/files/2232746/soul.blade.usa.v1.1.state.zip)

**Comment by saftle** [comment]
@iCatButler Ah I see, so then it also affects Final Doom, Hexen, and Star Wars Dark Forces as mentioned by @twinaphex here: https://github.com/libretro/beetle-psx-libretro/issues/43#issuecomment-220841693

**Comment by twinaphex** [comment]
@iCatButler Could you attempt making a diff patch that implements this? (looking for triangles that would be a single pixel high and converting them to quads that fill out the whole line at whatever scale) Once I have a diff that works for the problematic games (Soul Blade/Final Doom/Doom/Hexen), I could then look at figuring out a way we could  integrate this in the emulator, maybe on a per-game basis.

**Comment by iCatButler** [comment]
@twinaphex okay, I've implemented a hack that fixes the rendering in these games:
https://github.com/iCatButler/beetle-psx-libretro/commit/e6b22a114624b72d3f8e5722b3c3cf3a38b6fabc.patch

It takes effect before the geometry is passed to any of the renderers so works in OpenGL, Vulkan and Software. Due to the way the software renderer works it loops around and generates a second triangle rather than converting to a quad. It also prevents a second templated draw call being inlined thus saving about 1000KB being added to the .dll(!).

I've added a couple of checks to reduce false positives, one that takes advantage of PGXP to reject 3D geometry and another to reject small lines (currently hard coded to 3 pixels long). I'll do some more testing over the next couple of days to see how effective they are, but the image is largely clear of artifacts in games like Chrono Cross where Pete's implementation often falls down.

**Comment by iCatButler** [comment]
Update: The PGXP method works really well for removing false positives, even when using the software renderer. The obvious down side is that it won't work if you want to use a hardware renderer without PGXP and perspective correction enabled.

With the short line detection enabled at a suitably aggressive level (about 10 pixels) pretty much all of the false positives are caught on 3D games and the water in Soul Blade still renders correctly. Unfortunately this breaks games like Doom where gaps will reappear in distant surfaces.

I've implemented another test, that checks to see if texture coordinates describe a line, and that appears to be working really well. It doesn't cause issues with Doom or Soul Blade's water but does catch most of the false positives on 3D geometry. I'll see if I can improve on this method.

In the end, it's really just Soul Blade's water level that combines this technique with 3D geometry and so benefits from real time testing. Using a short list of game IDs in which to enable the hack might be the best solution in the long run to avoid false positives entirely, unless there are other games drawing lines in this way that haven't been flagged.

**Comment by iCatButler** [comment]
@twinaphex I ended up just rewriting the whole function to be more concise, assuming that the two vertices at the end of a line share the same UV makes it far easier: https://github.com/iCatButler/beetle-psx-libretro/commit/bc1696d170ad6295592ccf40b6055e42bafe6133

The output is also much cleaner than the previous version, or the PCSX-R plugins. Without PGXP perspective enabled to check there are a few false positives on 3D meshes in Soul Blade and Tomb Raider, but without modifying the code to highlight them in a contrasting colour I can't really see them.

I think that's probably about the best I can make it for now.

**Comment by twinaphex** [comment]
Awesome work @iCatButler !

I also think that it would still be worthwhile to have PGXP working for software rendering mode, even if some people believed in the past this would be slow, I still think it would be worthwhile from the perspective of being able to compare rendering results between software and hardware (GL/Vulkan) rendering modes.

**Comment by iCatButler** [comment]
@twinaphex given the standard precision x/y coordinates are upscaled before they're passed to the renderer I just realised you can overwrite them with the floating point values and get a limited form of PGXP.

The result is that precision scales with resolution, with the vertex positions being effectively truncated to fixed point values of increasing capacity. At 2x there's definitely a loss of detail and smooth motion over hardware, but at 4x the results stand up pretty well (although framerates in many games take a dive on my computer). There's obviously no perspective correction on textures either.

It's definitely not a full implementation, but for a quick hack it's interesting. Given the performance issues I can see a full implementation with perspective correct texturing being really slow without some sort of multithreaded rasterisation.

**Comment by twinaphex** [comment]
Works pretty well, the only thing that doesn't look correct still right now in Doom/Final Doom is the skybox.

Hexen seems to render fine.

Duke Nukem: Total Meltdown renders mostly fine but some of the geometry onscreen seems to suffer from ghosting, so maybe another specific hack going on there we need to figure out.

Star Wars: Dark Forces is actually completely glitched out (it was glitched out before as well), so it seems it uses a different trick for rendering a Doom-style DOS FPS to the screen than Doom PSX itself does.

Soul Blade's Li Long stage renders the water fine now.

**Comment by twinaphex** [comment]
I will turn this into a core option similar to how Pete's plugin did it.

**Comment by twinaphex** [comment]
It seems like the skybox glitching in Doom only happens with the GL renderer, Vulkan and software renderers are fine there.

**Comment by iCatButler** [comment]
It looks like the assumption regarding UV coordinates doesn't hold true for either Duke Nukem or Dark Forces, if I revert back to the old more aggressive algorithm without the UV checks it will render all the geometry in those games.

However, the textures are still completely messed up in Dark Forces and on the same surfaces in Duke Nukem that had ghosting. Software can render Dark Forces correctly at 1x and Duke Nukem at all scales. Going above 1x on Dark Forces introduces the garbled textures, like the UVs or VRAM have changed before the second triangle is rendered. It'll be interesting to know how that is even possible.

I can confirm that Pete's plugins have the same limitations too, so we're in good company.

**Comment by iCatButler** [comment]
Okay, I figured it out (I think...).

Using no$psx's debugger I peaked at the triangles being rendered by Dark Forces and it looks like the UVs describe arbitrary triangles rather than lines like Doom or Soul Blade, or even thin triangles. I think it relies on the PS1's UV interpolation rules to choose the correct samples when rendering the lines. I assume those defined by the upper left edge of the triangle, but I'll need to check.

When creating the second triangle the UVs are also flipped so it's sampling along a completely different edge and therefore getting completely wrong samples. It also means that the UV interpolation being done in hardware is probably wrong too, which is why the GL and Vulkan versions can't even render the original triangles correctly at 1x. The UVs probably need to be modified for those too.

**Comment by iCatButler** [comment]
Yeah, forcing the all vertices in both the original triangle and the flipped one to use the leftmost and uppermost original UVs fixes both Dark Forces and Duke Nukem in both hardware and software rendering. Both of these are using the GL renderer at 4x:
https://user-images.githubusercontent.com/17948959/43659735-d1275b12-9754-11e8-9f42-7369ecf5a856.png
https://user-images.githubusercontent.com/17948959/43659744-d9ee657e-9754-11e8-9d0a-26b50e61807b.png

This is just hacked in at the moment, I'll look at writing a new function to handle this a little better. It probably won't be as clean as the version that works on Doom and Soul Blade as there's less specific about the triangles involved and it modifies the existing geometry too.

**Comment by iCatButler** [comment]
@twinaphex I've implemented a second version of the hack to handle these more difficult games. I left the previous one as an option too because the new version is more aggressive, resulting in more false positives when trying to find line candidates. 
https://github.com/iCatButler/beetle-psx-libretro/commit/64d6f76267eec9c9c9ed87385560ec4d3c1bd814

I've changed the naming conventions a little, feel free to change them again if you can think of anything that better describes what this is doing.

I also appear to have left in the hacky software PGXP support (commented out).

**Comment by twinaphex** [comment]
Awesome work yet again. Let me get onto backporting it.

**Comment by twinaphex** [comment]
Yeah, this fixes both Duke Nukem: Total Meltdown and Star Wars: Dark Forces. Awesome. Let me try hooking up a UI/core option for toggling between these modes.

**Comment by iCatButler** [comment]
I think this might be solved with the latest commits adding the options to toggle behaviour.

**Comment by saftle** [comment]
Oh yes, you're right. Closing. Thanks everyone for working on this. Time to upscale Dark Forces :D
