### ISSUE TITLE
[CPU overclock] Harry Potter and the Chamber of Secrets [SLUS-01503] - input stops working when CPU overclock is above 140%

### ISSUE THREAD

**Issue by shikulja** [libretro/beetle-psx-libretro#425]
Harry Potter and the Chamber of Secrets [SLUS-01503]
In the main menu, control works, after the start of the game, the control of the main character is lost.
After several attempts, once I could run a little to the next game dialogue, after which the control again stop to work.
upd. beetle (sw) - control does not work at all (already on language selection)
upd2. not work when cpu overclock. if not important, you can close

**Comment by needo2** [comment]
IIRC this game doesn't recognize the controller on PS hardware if Dual Shock is enabled. Might be related to that.

**Comment by shikulja** [comment]
@rz5 Yes, when I expose 140% the log appears, at 150% the control is completely lost (the retroarh menu is working normally) Checked at the start of a new game.

**Comment by rz5** [comment]
I'll be closing this and marking it as wontfix because all of the overclock options are 'hacks'- they will most probably affect the emulator's compatibility with the software that ran on the real thing.

@simias - pinging you because you might be interested in knowing about this game and its response to CPU overclocking.
