### ISSUE TITLE
audio volume settings backward?! negative decibels

### ISSUE THREAD

**Issue by mick-p1982** [libretro/beetle-psx-libretro#442]
FWIW I think maybe Beetle's core is interpreting RetroArch's audio volume setting backward.

The volume is very loud, so I went searching for a fix. RA has the default at -80, which is quite muted, or should be. When it is set to -30 the sound is lowered, but it should get louder. When it is set to 0, which RA calls normal, the sound is muted. 

I think Beetle is interpreting 0 as off, and negative as positive.

**Comment by rz5** [comment]
@mick-p1982 - I can't replicate this issue.
On my end, if we're using RetroArch and we increase the value of Settings > Audio > Audio Volume Level (dB), it gets louder and quieter if we decrease it.

If you look at the retroarch.default.cfg file and search for audio_volume, you'll see the following:
![image](https://user-images.githubusercontent.com/8117159/47959559-4ac62200-dfdf-11e8-9ba4-665b817f251c.png)

The default values for both the audio volume and audio mixer volume are zero.

Are you changing the audio volume by highlighting the option and press left/right or are you selecting it (pressing Enter) and then selecting a value from the "drop down list"?

**Comment by mick-p1982** [comment]
Well, I'm referring to the UI's Audio->Audio Volume Level. So try that.

**Comment by rz5** [comment]
Thank you for the clarification.

Sorry to say but that's a frontend bug. That "list" thing is neat but it's new and it seems to have bugs still. 
So, instead of selecting a value from a list, just scroll with left/right/dpad while you have the option highlighted.

I'll tag the author of the feature and close the issue.
@twinaphex - Hi. The drop down lists feature is still buggy and works especially bad when used to change volume, so heads up.

**Comment by fr500** [comment]
The default is not -80 (you get the default value by pressing space)
Volume is always expressed like this, 0 should be the highest value, anything higher is artificial gain.

The "dropdown" implementation is terrible indeed

**Comment by twinaphex** [comment]
I have a hard time understanding why we are blaming the dropdown list now for this? I can set the volume level and set '0' just fine, and I don't see anything going obviously wrong.

So what is the issue here then?

There is legit criticism to be made about the dropdown list and some of the options not working with it (and I just fixed some unsigned integer-related issues), but I don't see this being one of them, or at least not for the reasons being cited here at least.

**Comment by mick-p1982** [comment]
I just made an issue here (https://github.com/libretro/RetroArch/issues/7560) not realizing this was being discussed still.

@twinaphex On my system, 0 mutes, and -80 is maximum volume. It seems to me that the menu is mislabeled according to the thinking the 0 is no volume, and large numbers are maximum. Because that's how people think about volume, and maybe how it should have been designed. 

Is English the first language of RetroArch? Maybe it's a translation problem, but still hard to believe... I wonder how long it's been this way unreported :)

**Comment by mick-p1982** [comment]
@fr500 My volume was very loud, and the menu defaulted to -80 and I'm pretty sure it was printed in the right hand column in the parent menu. And it sounded the same as when I chose -80. 

I chose 0 to see what maximum sounded like, and got no sound. I ended up choosing -30 as a happy medium (which should've been louder than the original setting.)
