### ISSUE TITLE
[Beetle PSX HW] Pixel aspect ratio should be 8:7 not 5:4 in 256px width mode

### ISSUE THREAD

**Issue by ggdrt** [libretro/beetle-psx-libretro#510]
## Description

Currently by default the core stretches 256px width framebuffers by 25% to a 320px width 4:3 display aspect ratio, which results in an incorrect 5:4 pixel aspect ratio. The correct pixel aspect ratio is 8:7 (~14.286% stretch), which all currently visible Mednafen releases on https://mednafen.github.io/releases/ (0.9.48 through 1.22.2) handle correctly. For a 256px width framebuffer this 8:7 PAR results in around a 1.22:1 DAR with 240 lines (alternatively 1.306:1 DAR with vertical overscan cropping to 224 lines). The missing width for the full 4:3 DAR should be horizontal overscan area, as shown in the image below. 

### Image of issue

The upper image demonstrates the current behavior on Beetle PSX HW while the lower image is the same title running on Mednafen 1.22.2 with expected behavior. The 2D character sprites and the portrait image on Beetle PSX HW are unnaturally squat.

![Image](https://i.imgur.com/TPCsvAL.png)

### Testing results

This has been an issue in the HW renderer for as far back as I can tell, and isn't handled correctly without the user manually setting the aspect ratio through the frontend. The issue seems to be irrespective of core options or Windows platform distributions (7 and 10 ver1709/1803/1809 tested). ~~#5 also brings up a similar issue four years ago, although the user's claims that the attempted manual solution resulted in the correct resolution are most definitely incorrect based on the calculations provided below.~~ (In the linked issue, software renderer was actually performing correct behavior.)  In any case, I'm not sure it would make sense to have end users use the RetroArch frontend to manually solve inaccurate behavior on the core side. 

I haven't had the time to verify scaling behavior for other width modes yet, but I wouldn't be surprised if the core also handles those incorrectly.

### Info dump

A lot of this information was strewn over the web in various places so I wanted to compile it together for thoroughness.

The sampling rate on an NTSC analog television for 1:1 PAR at 480i is 135/11 MHz. This sampling rate drops to 135/22 MHz for 1:1 PAR at 240p. The PS1 gpu is 53.69 MHz with a dotclock divider of 10 for 256px mode, resulting in pixels outputted at 5.369 MHz. So relative to this 135/22 MHz 1:1 PAR baseline, the PAR of the PS1 at 256px width is (135/22 MHz)/(5.369) ~= 1.1429 ~= 8/7. 

Alternatively, consider how many pixels fit into the 52.6 us active video portion of a scanline. We know from the above calculation that pixels are pushed at 5.369 MHz. This a total of (52.6 us)*(5.369 MHz) = 282.4094 pixels per active portion -- an extra 26.4px in width greater than our 256px framebuffer. We now need to fit this 282.4094px by 240px active image to a 4:3 display aspect ratio, the closest being 320px by 240px on modern displays. A stretch of 282.4094px to 320px is a factor of ~1.133, just 1% under an 8/7 stretch. The SNES similarly outputs a 256px width image with 24px of letterboxing, allegedly with a slightly shorter 52.148 us active video portion (https://wiki.nesdev.com/w/index.php/Overscan) but the same 8/7 stretch. 

The caveat here is the assumption that the GPU is not performing any interpolation for upsizing the 256px framebuffer to the full 282.4 pixel active portion. Considering that the GP1(06h) command shows that the framebuffer begins being displayed a number of pixel cycles into the active video portion and that it also finishes being displayed a number of pixel cycles before the end of that same portion rather than at the very edge, I think it's extremely unlikely there is any interpolation being done. If anything, the extra 26.4px is just horizontal overscan region to be cropped by television borders, similar to the 16 lines of vertical overscan cropped off the 240px framebuffer height.

### Some sources:
https://lurkertech.com/lg/video-systems/
https://www.maximintegrated.com/en/app-notes/index.mvp/id/734
https://problemkaputt.de/psx-spx.htm

**Comment by rz5** [comment]
@ggdrt Does the software renderer not have these problems?

**Comment by ggdrt** [comment]
Sorry, I should have remembered to test that earlier. The software renderer doesn't have these problems. It's an issue in both the GL and Vulkan HW renderers. I've changed the issue title to reflect this.

**Comment by ggdrt** [comment]
Sorry, I forgot to specify in the post. The software renderer doesn't have these problems. It's an issue in both the GL and Vulkan HW renderers. I've changed the issue title to reflect this.

**Comment by ggdrt** [comment]
Fixed in GL renderer by implementing crop overscan option as of 7e76756.

Still needs implementing for Vulkan renderer.

**Comment by bajolzas** [comment]
Just wanted to note, that megaman x3 also has a ratio of 8:7 like its snes counterpart; but the crop overscan option doesnt quite bring it to 8:7.
In plugin based emulators using PeteOpenGL2 plugin, this aspect can be reached be using the "keep aspect raio" on its settings.
Not sure if this can be fixed on the beetle side but I thought it was worth mentioning.

**Comment by ggdrt** [comment]
@bajolzas I'm not quite sure what you mean, can you be more specific? Having screenshots to demonstrate this would be helpful.

For one, the PAL region version of X3 is going to look wider than the NTSC-J version of X3. That is accurate because of PAL has a higher vertical resolution at the same 4:3 aspect ratio.

Additionally, I believe that Pete's OpenGL2 plugin is not accurate for display aspect ratios and pixel aspect ratios. I don't think it's a good comparison to make.

Currently if you set the Crop Overscan option to **Off**, games that have a 8:7 pixel aspect ratio will display correctly for Beetle. With the option set to **On**, the game will be stretched -- this is known and is being worked on.

**Comment by bajolzas** [comment]
its the PAL version converted to 60hz.
I've tested changing the aspect ratio in retroarch to a fixed 8:7, and that along with the crop overscan option off seems to match the ratio of the snes version on bsnes without aspect correction, so it seems it is simply not cropping enough I guess...?

 Pete's OpenGL2 may not be accurate on a lot of stuff but it matches the snes version ratio of 8:7 as well with said setting.

**Comment by ggdrt** [comment]
Okay, a couple things. 

Firstly, beetle does not fully support 60hz-converted PAL titles. We can't guarantee correct behavior in all instances and that's something that is a separate issue already open in the tracker. That being said, this seems to look like it's working so on to the next point.

Secondly, this looks to me like it's working as it should. Bsnes with Aspect Correction **On** should match Beetle PSX HW with Crop Overscan **Off**. You have to understand that bsnes with Aspect Correction turned off is not what will be seen on output from original SNES hardware. I can absolutely guarantee you that Pete's OpenGL2 plugin is not displaying at the proper aspect ratio. 

You are reporting a different issue/request from this thread. This thread is talking about how the proper pillarboxing at 4:3 display aspect ratio is missing. You are asking for a 1:1 pixel aspect ratio mode.

**Comment by bajolzas** [comment]
Fair enough I'll open another issue then.

**Comment by ggdrt** [comment]
Display range is now fixed for this issue, only remaining problem should be geometry which is being worked on.

**Comment by ggdrt** [comment]
Automatic aspect ratio correction feature merged in on 04daeef, issue can now be closed.

**Comment by ser-pounce** [comment]
I was messing around with Vagrant Story recently, and noticed that things seemed slightly stretched horizontally. After falling into a bit of a rabbit hole I emerged with some interesting data that confirms the original bug, but with better precision. It might already be known but I couldn't find it spelled out step by step anywhere, so I'd like to share it here just in case.

Some definitions first for completeness.

NTSC spec
- Color frequency: 3,579,545.45 (5000000 * 63 / 88)
- Line frequency: 15,734.27 (2/455 * color frequency)

Rec. 601
- Samples / line: 858
- Active line samples: 720 (includes 16 sample tolerance)

PS1
- PS1 NTSC video clock: 53,693,181.82 (NTSC color frequency * 15)
- Ticks per line: 3,412.5 (video clock / NTSC line frequency)
- Ticks drawn on screen: 2,560 (at least for 256 and 512 width modes)

Now, Rec. 601 calls for 720 samples at 13.5 MHz to correctly capture all potential information, however this is to account for a certain amount of variance in analog systems. The most accurate number of samples required assuming a perfect signal is actually 704 ([calculations here](https://en.wikipedia.org/wiki/Pixel_aspect_ratio#Digital_video_processing)), and it stands to reason then that 858:704 would be the ratio needed when converting a digital signal to an analog one.

If we take the 3,412.5 PS1 tick rate per line, divide by 858, and multiply by 704 we get *exactly* 2,800, and I think Beetle already uses this value to calculate the aspect ratio.

This also means the pixel aspect ratio isn't approximately 8:7, it's *exactly* 8:7, assuming again that the timings were based on Rec. 601. The active line period is 1 / line frequency / 858 * 704, which yields approx. 52.15μs (instead of 52.6μs in the first post). Using the same calculation as the first post, multiplying this by the pixel frequency (@256px = video clock / 10) yields *exactly* 280 instead of 282.4.

Finally to show you what led me here, here's the title screen for Vagrant Story displayed with the above calculations (585 x 448px), and again after having been scaled to what was probably meant to be the correct aspect ratio (573 x 448px); I drew a circle on both to help.

![Native](https://user-images.githubusercontent.com/655122/151714501-ace24c87-06f8-40dd-b78d-cb7edccdc3cf.png)

![Corrected](https://user-images.githubusercontent.com/655122/151714505-e2971b30-8305-42ae-a3df-cc7535c7f507.png)

What I think is going on here is that although the PS1 video output seems to be based on a 858:704 active line period, the tooling used during production was actually targeting 858:720! This is not from some mom & pop shop either (Squaresoft), so there may well be more games that are affected.
