### ISSUE TITLE
Retroarches Disk Control not working on Beetle PSX (both hardware and software)

### ISSUE THREAD

**Issue by medievil1** [libretro/beetle-psx-libretro#523]
## Description

Retroarches Disk Control not working on Beetle PSX (both hardware and software)
When loading second disk image, beetle does not recognize it

### Expected behavior

when you cycle tray/append second disk image it SHOULD continue game

### Actual behavior

cycle tray image, append second disk, hit start, x  various buttons,  beetle never recognizes change and still asks for second disk (or first if you test by loading second disk initially)
### Steps to reproduce the bug
Easiest
1. boot second disk image (Chrono cross disk 2 for example)
2. select new game
3. when it asks for disk 1, access quick menu, go to disk control, cycle tray then append disk 1 image..hit all buttons to see if it recognizes disk
### Bisect Results

unknown, first time trying it

### Version/Commit
[If you're using RetroArch, after the core has started, this information is on the bottom left]

- Beetle PSX: HW version 0.9.44.1 a264b2b

### Core options
resolution, pgxp, crop overscan
### Environment information

- OS: windows 10 64bit (1809)
- Compiler: N/A
- GPU: GTX 1660

**Comment by medievil1** [comment]
additional information... a cause for the issue...
seems to work IF you cycle the tray, exit disk control and resume game, then go back into disk control and append second image... simple solution would be to internally for a micro second, resume the game on a tray cycle

**Comment by rz5** [comment]
@medievil1 - On beetle-psx, running _Disk Cycle Tray Status_ disc control action **only once** will cause the following:  if the tray/disc was closed/ejected, now it's opened/inserted. 
In the real console, the CD drive won't spin its disc if the tray is opened. Beetle-psx has the same behavior so you need to run _Disk Cycle Tray Status_ **again** after running _Disk Image Append_, thereby closing beetle-psx's virtual disc tray.

I think I'm right about this so could you please re-test it.

Thinking about this, offering you fine grained functions that let you to leave the tray opened allows replicating some exploits you can do on the real console e.g. in FF7, after casting Regen on your characters, if you open the disc tray and leave it open, the game will keep ticking, Regen will still be healing but the next turn is effectively paused because the game needs to read from disc to get animation data.

But if enough people can't figure out how to use the Disk Control options, perhaps a compound action (aptly named Change Disc) should be offered that receives a disc image and does the tray status cycling for you, in the correct order.

**Comment by ggdrt** [comment]
@jdgleaver Is this issue is still valid? The commit history says new disk control support was added last month and it looks like the Disk Cycle Tray Status and Disk Image Append controls are deprecated in RetroArch (tested on 1.8.4 stable).

**Comment by jdgleaver** [comment]
No, this doesn't seem to be valid any more.

The updated disk control interface basically enforces correct operation - but note that the renamed `Load New Disk` (used to be `Disk Image Append`) option is not recommended at all. I consider this a legacy feature, and would have removed it entirely (but too many users would have complained...).

Everyone should always use `m3u` playlists for multi-disk content. Always, for every core that supports them. There are no issues at all when swapping disks loaded via `m3u` files.

**Comment by ggdrt** [comment]
Good to know, thanks. I'll update the core documentation accordingly.
