### ISSUE TITLE
[Feature Request]1:1 pixel aspect ratio mode

### ISSUE THREAD

**Issue by bajolzas** [libretro/beetle-psx-libretro#561]
This has already been discussed at #510
Id like beetle to be able to allways output in a 1:1 pixel ratio in every instance.

Pete's OpenGL2 plugin as a similar setting, namely stretching mode: scale to window size, keep aspect ratio, that seems to achieve this, or at least close enough.
In Megaman X3 (converted to 60hz) it even matches its snes counterpart running in bsnes without aspect correction. (I know snes is supposed to output in 4:3, but it renders at 8:7, or 1:1 pixels, and it looks so much better to me)

for reference:
bsnes aspect correction off
![megaman x3 bsnes](https://user-images.githubusercontent.com/51722671/68510003-525f7d00-026a-11ea-8278-01b8b1ad3d85.png)

pcsxr-pgxp Pete's OpenGL2 stretching mode: scale to window size, keep aspect ratio (fmv's  are 4:3 or close to it)
![megaman x3 pcsxr](https://user-images.githubusercontent.com/51722671/68510041-630ff300-026a-11ea-8641-53f9b0e016d0.png)

bettle psx hw opengl aspect ratio: core provided, crop overscan:off
![megaman x3 beetle](https://user-images.githubusercontent.com/51722671/68510059-6d31f180-026a-11ea-93c1-edddd9cd2936.png)

**Comment by rz5** [comment]
@bajolzas If you are using RetroArch as your frontend, in Settings > Video, you will find this:
![image](https://user-images.githubusercontent.com/8117159/68530450-1d9e0500-0300-11ea-8d96-5918f3f53a39.png)

In other words, RetroArch allows you to override what the core provided aspect ratio already. Now, this core could give you a toggle to turn off the 4:3 (or 16:9 if using widescreen hacks) DAR...you actually want that, given the existence of the RetroArch feature?

**Comment by bajolzas** [comment]
well it still outputs in 4:3, even tried tekken 3 as you are using, and that screen is 4:3 as well, maybe something else is wrong on my side then :/

**Comment by rz5** [comment]
@bajolzas Ah, I see what's going on. My fault on not being clear on what I was showing.

My screenshot is from a build of the r5/sw-renderer-set-geometry branch. Currently, in the master branch, beetle-psx is always reporting a base geometry of 320x240 (320/240 = 1.33 => 4:3 PAR).

Because of this, when you ask RetroArch to override the aspect ratio to 1:1 PAR, the "incorrect" base geometry values are used and you're still stuck at 4:3...

That specific branch is trying to tackle this bug. And as you see, Tekken 3 (PAL version) renders at 400x576 (25:6 ratio) and RetroArch can now correctly detect that to force a 25:6 DAR when you ask it for 1:1 PAR. And well...as you can see, sometimes 1:1 PAR isn't a good idea:
![Tekken 3 (Europe)-191109-155029](https://user-images.githubusercontent.com/8117159/68531483-74a8d780-030a-11ea-922e-cd7d3a699605.png)

**Comment by bajolzas** [comment]
sure, it may not be the best option for tekken 3, but in my opinion it is for megaman x3, and possibly for other games as well, so its allways good to have the option. Nice you are already working on it then.

**Comment by ggdrt** [comment]
@bajolzas Sorry for the delay, this is now implemented as of 04daeef. You can find this via going to core options and changing `Core Aspect Ratio` to `Uncorrected`.
