### ISSUE TITLE
Unable to full stretch with overscan options

### ISSUE THREAD

**Issue by backgamon** [libretro/beetle-psx-libretro#580]
### Description

[Description of the bug]
I'm unable to full stretch the screen on some PAL games, a black border are impossible to erease. 
### Expected behavior
Full screen without any black bar:
![retroarch 2019-12-25 14-31-53-244](https://user-images.githubusercontent.com/39404647/71446450-c1623980-2723-11ea-9f7f-6ef0848280cb.jpg)
Retroarch 1.7.7
Psx Beetle HW 0.9.44.1 c933402

### Actual behavior
With only crop overscan:
![retroarch 2019-12-25 14-25-24-955](https://user-images.githubusercontent.com/39404647/71446476-1605b480-2724-11ea-9b1e-b03e4b71f9ed.jpg)
With crop overscan + horizontal image offset at max for the left (-24):
![retroarch 2019-12-25 14-26-49-179](https://user-images.githubusercontent.com/39404647/71446491-3c2b5480-2724-11ea-88c5-2871d815c8d9.jpg)
![retroarch 2019-12-25 14-26-57-127](https://user-images.githubusercontent.com/39404647/71446493-40f00880-2724-11ea-8318-df287a1fccd6.jpg)

### Steps to reproduce the bug

1. Launch a Pal game (Destruction Deby Raw for the ex)
2. [see the result

### Version/Commit
Retroarch 1.8.1

- Beetle PSX: [version/commit]
Psx Beetle HW 0.9.44.1 8cdfd50

### Core options
Just look picture before

### Environment information

Windows 10 Pro x64 1909 (18363.535)
Gigabyte 2070 RTX 8 Go OC - 441.66

**Comment by backgamon** [comment]
I guess (for me) the best can be a option/switch to enable or disable the new scaling system.

**Comment by rz5** [comment]
@backgamon On this game's main menu, if you go to Options and Video, you'll be able to adjust the screen position. Using that in conjuction with the image offset (cycles) to -24, you'll achieve a slimmer border.
![Destruction Derby Raw (Europe) (En,Fr,De,Es,It)-191225-203429](https://user-images.githubusercontent.com/8117159/71450243-fedfba80-2755-11ea-8a35-f16c756f3cc6.png)

@ggdrt For this game, using the SW renderer I need to increase the `image_offset` core option to `-8px` in order to get a colored line to fill the whole width of the screen. 
Similarly, for the Vulkan renderer the `image_offset_cycles` needed to be increased to `-29`.

So these two core options are due for a increase to its limits, maybe +/- 20 pixels and +/- 40 cycles to catch any future problematic PAL game.
