### ISSUE TITLE
Disney's Donald Duck: Goin' Quackers (Skip intro movie)

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-psx-libretro#583]
Hi, here I leave a mistake I found.

In the game Disney's Donald Duck: Goin 'Quackers, when you press Start, a video of a plant appears, but only a few seconds and the video skips instead of continuing. This happens in Bettle PSX and HW, but in PCSX Rearmed it works fine. I also tried it with the latest version of Mednafen, 1.24.0 and it also works correctly.

As I said in another post, this emulator was somewhat outdated, based on 0.9.44.1 and it would be nice to update it to a newer one.

Apparently, an attempt was made to upgrade to 1.22.0, but something happened and it seems that it still does not work properly.

Obviously everything is tested with the latest Nightly version of Retroarch and the latest cores to date of this post.

I leave it here to record the error.

Thank you.

**Comment by rz5** [comment]
Related to #487

**Comment by rz5** [comment]
@ToniBC - When exactly does the bug happen? Can you post a picture of how it looks in-game? When I press the 'start' button while Donald is in a level, it brings up a cartoon TV.

Are you talking about FMVs?

**Comment by ToniBC** [comment]
I have tried with all the options and I cannot solve it, with PCSX Rearmed the same iso works without problems, but with Beetle PSX / HW it is always cut. Another user with the same problem told me, always at the same point.

https://youtu.be/2The0KrPC-U

There I show the options, I also tried all the CD access, asynchronous as you have it in the images and the same thing always happens.

**Comment by rz5** [comment]
@ToniBC - Could you retest again, but this time make sure Quick Menu > Controls > Port 1 Controls > Device Type is set to `PlayStation Controller`

**Comment by ToniBC** [comment]
Yes, it was that, when you put the control on PlayStation Controller you do not skip the videos, curious. The error seemed as if the button was pressed, but I never tried that. Thank you so much.

Tomorrow I will make a video explaining the error on my channel.

**Comment by ichee** [comment]
Controller can still be set to Dualshock without the intro being skipped if  `Enable Dualshock Analog Mode Toggle`  is enabled, so long as the toggle combo is not triggered during the intro fmv, although manually triggering the combo is unnecessary since this game force enables analog at the title screen.

Issue seems likely related to the fact that this game, among others, can force enable analog on its own if a dualshock is detected.

Issue on original hardware was likely prevented, or never noticed, due to the fact that games that force enable analog mode prevented analog from being toggled off.
