### ISSUE TITLE
Android Beetle PSX HW - Unable to find or open hardware rendererrenderer 

### ISSUE THREAD

**Issue by MegaDeox** [libretro/beetle-psx-libretro#614]
## Description

When trying to load any game with the hardware renderer, I get a black screen and the message "Unable to find or open hardware renderer for frontend". Both gl and Vulkan produce this. Software renderer works fine.

### Expected behavior
 
The games should work.

### Actual behaviour

...they don't.

### Steps to reproduce the bug

1. Choose the hardware renderer.
2. Load a game.

### Bisect Results

It started a week ago. I heard from @ggdrt that this area of the code was changed recently. 

### Version/Commit
I'm on the latest version as far as I know (1.8.4, 0.9.44.1 62b6333).

### Core options
I tried messing with the new dynarec, but all of the options produce the same result.

### Environment information
Samsung Galaxy Note 9, Exynos version.

**Comment by ggdrt** [comment]
For the "Renderer (Restart)" core option, what do you have it set to, and importantly what does your frontend's video driver set to? In RetroArch you can find this by looking at Settings -> Drivers -> Video.

**Comment by MegaDeox** [comment]
@ggdrt as I wrote, hardware renderer, and both Vulkan and gl produce the same result.

**Comment by ggdrt** [comment]
Like @rz5 mentioned in that previous closed issue, the core is not built with GL support on Android.

The new `Hardware (Auto)` option is the same as the `Hardware` option in previous versions of the core. It attempts to run a hardware renderer for what your frontend requests. Because your frontend is requesting the GL renderer but the Android core does not have support for it, you will receive the warning in your original post.

Similarly, forcing the GL renderer through the core options when the core is built without GL support will give you the second warning that you mentioned. So the core options are working as expected.

If you're unsatisfied with the Vulkan renderer you could alternatively run core in Software mode instead. The Vulkan renderer does have bugs, but the issues are typically much less severe than the GL renderer.

**Comment by MegaDeox** [comment]
How is that possible? I spent a lot of time with this core, and the performance was clearly better with the hardware renderer than the software, and I didn't have any bugs, so it didn't fallback to Vulkan.

**Comment by rz5** [comment]
@MegaDeox - Specifically about this bug: you CAN get something other than a black screen and you do NOT get the "unable to find hw renderer for frontend" message, correct? 

Please consider opening a new bug report about whatever bugs you currently have with the Vulkan renderer on Android and go into as much detail as you can. Just be aware that we already know of #600.

About this core being slower: there's several moving parts to verify first before making that statement. 
Your OS, drivers and/or background apps could have updated and introduced bugs or more performance overhead, it could be a combination of these; 
RetroArch has been getting updates, it could be that as well...

But despite those moving parts, you now also have access to a CPU dynarec option that should get you back into fullspeed. Test that out as well.

**Comment by MegaDeox** [comment]
@rz5 I did try the dynarec, still 40 fps.
I really don't think anything changed on my end. The core worked fine, I updated it, and It stopped working.

I think I already opened a bug for the Vulkan thing a few months back, I'll try to find it.

**Comment by rz5** [comment]
@MegaDeox - I need you to be specific on this: does it still not work for you on your end? You're still getting the black screen and error message as described on your original post?

**Comment by MegaDeox** [comment]
@rz5 The error I described in the OP did not use to happen. What happened was I had the renderer set to hardware, with gl, and everything worked fine.
Then I updated. The aforementioned scenario gives me the error in the OP. Setting the backend to Vulkan gives me graphical glitches, like before the update. Setting the renderer to software gives me poor performance, like before the update. Playing around with the dynarec does not help the performance with the software renderer.

**Comment by ggdrt** [comment]
You didn't use to get that error because the fallback handling wasn't even working properly back then. Prior to 2efd828 the `Hardware` setting would always force the Vulkan renderer. Between 2efd828 and 748d4f8, the `Hardware` setting would force the Vulkan renderer in any case where the frontend driver was not OpenGL. Because the Android build does not even have the checks for initializing a GL renderer built into it, I am highly certain that you were falling back to either the Vulkan renderer or software renderer (at 1x resolution), depending on whether or not your frontend at the time had support for requesting a specific renderer from the core.

**Comment by MegaDeox** [comment]
@ggdrt but you're missing the fact I didn't get graphical glitches or slowdown on 1x. I was even able to bump to 2x in some games. There had to have been a difference.

**Comment by rz5** [comment]
@MegaDeox - In #593, @tabnk did say he had lower performance when using the Vulkan renderer. Lower performance should be expected because the hardware renderers run on top of the software renderer (as opposed to one replacing the other).

IMO, you were most likely using the software renderer all this time. But we can test. If you give me a reasonable time frame where you remember it "working" as you remember it, I can share an older Android build.

**Comment by MegaDeox** [comment]
@rz5 sure, I appreciate it.
I'm certain it was fine two weeks ago. Probably a week ago as well, but let's go with two weeks.

**Comment by rz5** [comment]
@MegaDeox - [mednafen_psx_hw_libretro_android.zip](https://github.com/libretro/beetle-psx-libretro/files/4237955/mednafen_psx_hw_libretro_android.zip)

This is a build of d63a7aaf52f8d82848ca78149f2cb4eb3a3fc629, from December 14, before the dynarec was added in.

**Comment by MegaDeox** [comment]
@rz5 thanks, but how do I apply it?
As far as I know you can't access the cores folder on Android, if you're not rooted (which I'm not). When I tested the core previously I entered a different url in a config somewhere, I think. Is that possible?

**Comment by rz5** [comment]
Drag it to some folder that RA can see. In RA, go to "Load Core > Install or Restore a Core", navigate to your chosen folder and select the core. Your copy of beetle-psx-hw should have been rewritten with the older core. When the core is loaded, you should see `d63a7aa` as part of the core's name.

**Comment by MegaDeox** [comment]
@rz5 for some reason the commit isn't shown at all at the bottom left, but the renderer options are software and hardware like they used to, and there aren't any dynarec options, so I assume it's older.

Anyway, with Hardware and gl, I'm getting the "unable to find" error, which is weird. The Vulkan option is the same as well, and the software option runs slow. This behaves exactly like the new version. I don't know what to tell you.

**Comment by xfechx** [comment]
Hello,

I am getting the same error in Nvidia Shield TV.

No HW renderer found, falling back to software...

**Comment by xfechx** [comment]
I am getting the same error on NVIDIA Shield TV. Cannot run games with HW renderer. Falls back to software renderer each time.

**Comment by rz5** [comment]
@xfechx - Please check and report back these 3 things:

1) In RetroArch, what is "Settings > Drivers > Video" set to?;
2) Is "Settings > Core > Allow cores to switch the video driver" on?;
3) What is the "Renderer (Restart)" core option set to;

**Comment by xfechx** [comment]
1. GL
2. Yes
3. Hardware
