### ISSUE TITLE
Auto crop for PAL games.

### ISSUE THREAD

**Issue by backgamon** [libretro/beetle-psx-libretro#719]
Since https://github.com/libretro/beetle-psx-libretro/commit/706a4e6f9c81f32564112d69e8731a2899399ea4 black bars show on many PAL games.
A option are added for cropping, but many need a differents values for each.
It almost never be perfect...

### Expected behavior

No black bars same as https://github.com/libretro/beetle-psx-libretro/commit/79935274c2f990a962a8c6a111fb1f49f7bf1d46.

### Steps to reproduce the bug

Just launch any PAL games on latest build.

### Bisect results

I compiled a old version with some of the new change (XBR and textures correcting), but i'm unable to add all changes like Lightrec and RSX...
There are any chances to add a option/switch to disable (or enable) a system like the older?
Same as Duckstation:
![crop](https://user-images.githubusercontent.com/39404647/93019833-d0eb2080-f5d9-11ea-895e-9181ed769b16.jpg)

### Environment information

Retroarch 1.9.0
Windows 10 Pro x64 [19041.508]
Gigabyte 2070 RTX 8G OC [452.06]

**Comment by IngwiePhoenix** [comment]
Definitively having the same issue. I switched from DuckStation to this core - because it actually supports SBI files. DuckStation does not. Many of my PAL rips actually need that (Crash Bash being one of these).

I enabled the frame display. It fits pretty snug into that border, ironically.
![image](https://user-images.githubusercontent.com/2893716/93543761-bd82e100-f95c-11ea-9783-9041b0d45ba5.png)

An option to get rid of those would be nice. That with 16:9 and upscaled internal renderer is pretty amazing.

But those bars...kinda annoy me. My TV is an old 55" from 2011 and already has thick bezels - I don't need any more than I already have. :)

**Comment by backgamon** [comment]
For who want a old version[18 october2019] with all correction about XBR and Corrupted texture:

https://mega.nz/file/92hhxBCD#sBf0N6M9-H7K5xML0AZkvjBjCouvtNGhn4050YzAocc

Lightrec and all new change (except correction) are unavailable...i can't add...

**Comment by ds22x** [comment]
I believe this has been solved now.
