### ISSUE TITLE
Missing Layer after Update

### ISSUE THREAD

**Issue by Figuera** [libretro/beetle-psx-libretro#728]
## Description

I was directed by a user from libretro forums to post the bug here. The problem happened to another user as you can see in the original post (https://forums.libretro.com/t/missing-text-layer-in-beetle-psx/30190)

I'm playing Vagrant Story, the following picture shows the missing elements:

![bug1](https://user-images.githubusercontent.com/703016/93692997-04411a00-fac8-11ea-9f42-11f9a0a8351a.png)

This would be the expected behaviour:

![correct1](https://user-images.githubusercontent.com/703016/93693240-44ee6280-facb-11ea-94ea-53b4931b7f93.png)

I think this is a "layer" problem because it also affects other elements, the select arrow is missing in the select you memory card screen:

![bug2](https://user-images.githubusercontent.com/703016/93693191-626efc80-faca-11ea-9dc4-4acbb5cee9b0.png)

This would be the expected behaviour:

![correct2](https://user-images.githubusercontent.com/703016/93693217-f0e37e00-faca-11ea-835f-b87f758ac78c.png)

### Steps to reproduce the bug

1. Open Vagrant Story
2. Click Continue
3. Note the missing arrow from the selection your memory card menu

### Bisect results - Version/Commit

This started after my arch linux updated Beetle PSX HW from version `0.9.44.1/9f126e5`  to  `0.9.44.1/ab51d46`. Reversing the update solve the issue.

### Core options

I do use some customazible options for Vagrant Story, but I was able to replicate the bug using the default.

### Environment information

- Frontend: Libretro (?)
- OS: Arch Linux
- GPU: RX 570 (amdgpu 19.1.0)

**Comment by xzn** [comment]
Sorry that was my fault for not testing my PR thoroughly.

This issue should've been fixed by b162646 (the commit message is misleading, the fix is in [this line](https://github.com/libretro/beetle-psx-libretro/commit/b16264646dd494e8f97a7aed9f2ccf6b3a9df78c#diff-5dfb22247554410c870c7ddc6a7069aeR2013)) though you'd probably want to use at least 6124a06 which fixed another transparency bug introduced in version you mentioned.

Also skip 7a26d73 if you're planning to use a later version since that one's bad also.

Since I don't know when Arch will update its package sticking to an older version should work for now.
Alternatively use `asp` to build your own later version if you don't mind the trouble.

**Comment by Blakrajder** [comment]
I don't have it on the test custom core 85913a70 that @xzn provided for fixing black outlines in Vagrant Story.
Nightly official core ab51d46 that I use now also doesn't show the error OP @Figuera describes.
Those are over a week old builds though.

**Comment by rz5** [comment]
Fixed by b16264646dd494e8f97a7aed9f2ccf6b3a9df78c.

**Comment by Figuera** [comment]
Thank you for your great work. I will wait for the next Arch linux update to upgrade.
