### ISSUE TITLE
[Feature Request] Allow user mapping of DualShock Analog Mode Toggle

### ISSUE THREAD

**Issue by ichee** [libretro/beetle-psx-libretro#738]
It would be useful to allow custom configuration of `DualShock Analog Mode Toggle`, especially if users have an extra button to spare, or they wish to map to the middle button on their controller, retroarch menu defaults aside.

Also, the default mapping of `Start+Select+R1+L1+R2+L2` is also the command for soft-reset in many games, some of which only require a single press to reset.

**Comment by bslenul** [comment]
I'm not a dev so I could be completely wrong, but because of how RetroArch's "RetroPad" concept works I'm not sure it'd be really to implement.

A good alternative IMO would be to change the "Enable DualShock Analog Mode Toggle" core option from being a simple toggle to a "choice option", I mean clicking it would give you multiple options like "OFF" of course but also different preset combos like "Start+Select+L1+L2+R1+R2", "Hold Select for 2 seconds", "L3+R3", etc. for example, that would be really nice!

Pretty much like how the RetroArch `Settings > Input > Hotkeys > Menu Toggle Gamepad Combo` option works.

**Comment by IdiotBlueMage** [comment]
Holding the start button also turns off some controllers, making that button a bit of an issue sometimes.  I agree with the selection, the Final Burn Neo core has a similar method for how to access the bios menu.

I would suggest that "Hold L1+L2+R1+R2" would be the default, as L3+R3 is used in Ape Escape.

**Comment by negativeExponent** [comment]
does analog mode toggle even works? the core option description states that when ON, you should be able to switch ON or OFF with the L1+L2+R2+R1+Select+Start buttons, but nothing happens. games still works with both analog and dpad. An osd notification should show when the mode changes when using dualshock, but this only appears during loading of core.

**Comment by bslenul** [comment]
I just tried in MGS and it works as intended for me, the notification appears when I turn it ON/OFF (you have to hold the buttons for a few seconds) and when it's OFF my analog doesn't work anymore.

**Comment by negativeExponent** [comment]
must be game specific. KoroKoroNin want analog mode to be initialized and on analog mode always (based on my findings on pcsx). Even when holding said buttons, the notification appears but its always is Analog OFF, sticks On.. game still reacts to the analog stick

**Comment by bslenul** [comment]
The notification says "Analog toggle ENABLED/DISABLED" (the core option) and "sticks ON/OFF" (the 2 analogs on the controller). At least that's how I'm understanding it... :p

So if I'm correct, R4 has the normal behavior, the core option is enabled and then it enables/disables the 2 "sticks". For KoroKoro Post nin however it's weird yeah:

![image](https://user-images.githubusercontent.com/33353403/98097333-2bdc1e00-1e8d-11eb-870b-44922ad54578.png)

It looks like it disables the core option automatically (even if visually it's still ON in the core options menu) and because of that the sticks are forced to be always ON. Idk why it says "2 Analog toggle is DISABLED" tho, the "2" is probably just a typo? Not a dev so no idea what it means, but maybe it'll make sense for you, seems to be here:
https://github.com/libretro/beetle-psx-libretro/blob/c6ee7ce49551fadcff96cbbe26299646e6890b1e/mednafen/psx/input/dualshock.cpp#L199-L208

Same thing happens with Ape Escape so my guess is: some games simply force the sticks to be always ON if a DualShock is plugged (I mean even on the real hardware), you can even see the sticks switching ON automatically after the BIOS logos, which doesn't happen with MGS and R4 for example. So the core simply forces the sticks by disabling the "Analog toggle" mode (again, just a guess).

**Comment by ichee** [comment]
A method for doing this has been available upstream since version 0.9.41.

Mednafen forum discussion is [here](https://forum.fobby.net/index.php?t=msg&goto=4771&).

Option in code is called `psx.input.analog_mode_ct.compare` located in the`psx.cpp` file.

**Comment by BParks21** [comment]
I would really like to see an easy toggle solution. Sucks when games soft reset using the current combo.

**Comment by ichee** [comment]
Effectively fixed by #859, although exposing the analog button for mapping like all other buttons would be more ideal.
