### ISSUE TITLE
[feature request] Optimizing psx iso

### ISSUE THREAD

**Issue by yreb** [libretro/beetle-psx-libretro#77]
Hello

I used emulator since ten years. Here is a feature that could be very useful for libretro psx emulator: optimize game into a compatible format.

For exemple:

This option could be incredible when you talk of psx iso. Many pc plugin or emulator allow some modifications to your iso.

In compression (sometimes decompression on the fly needs bigger CPU)

compress to bz2 format (cdr mooby 2 plugin for PsX)
compress to 7z
compress to zip
compress to pbp or to multi pbp file
To gain some place, they also tried some exotic thing (on pc) this modification works on some andorid / linux emulator.

convert XA audio stream to mp3.
Delete/compress dummy files
Other drastic option exist (wipe video data / wipe audio data) (that option is clearly stupid)

Some times they also used index files to link the file to the compressed iso the emulator

Other path could be explored to gain some precious place and cpu usage , convert sony video PSX files to a newer and better compressed format.

Adding a way to do that optimizations safely and easily on your iso would be wonderful (we could gain place / cpu usage with a good compatibility) 
=> the device could do it at his own rythm ( even i f the process needs one or two hours per iso)

That thing could be done for psp iso and perhaps one day gamecube and wii iso (like the wbfs format)

**Comment by yreb** [comment]
libretro is developped for a wide type of device including tablet/phone cpos. That devices are limited in storage space.

I tried many of this trick on my isos and it seems to work with some emulator whitout a huge increase in decoding time. (psx emulators are port of PC emulator)

Some of this optimizations could speed up emulation:

convert XA audio file to mp3 could lead to an easier and hardware way to decode audio PSX game. (Less software/ More hardware)
convert psx video file .str to an other format which is commonly hardware supported too
Convert image and texture with a lossless optimization 

Adding an option in bettle psx which do automatically that work would be great
1st: the script convert file, delete dummys and modifiy the index of the iso
2nd He tried different way to compress it (sometimes bz2 is better than pbp or other format, but there is no rule)

**Comment by GM-Script-Writer-62850** [comment]
you can run the games compressed via a squashfs 
http://tldp.org/HOWTO/SquashFS-HOWTO/creatingandusing.html
a squshfs mount point is readonly once mounted, set the system to save your data to a non-default location; this saved me over 20GB using the xz compression algorithm (75 games; 10 multi-disk games) (52min to compress)
i doubt you can mount a squashfs on a phone/tablet without rooting it though

**Comment by simias** [comment]
So practically speaking, IMO the main issue with compressed CD formats is that they're all more or less terrible:

* "Dummy" general purpose compression like zip/gzip/xz and friends work pretty well for many ROM formats but they perform pretty poorly for CD images because the ECC and audio tracks will compress very poorly. Moreover they don't allow for easy random sector access so you have to decompress everything prior to starting the emulation. That can be pretty slow depending on your CPU specs, compression algorithm and size of the disc.

* Removing the ECC data prior to compression would help. It's what the "ECM" format is about, unfortunately this particular format also makes random sector access impossible. It also doesn't do anything for the audio tracks, those will still compress as poorly as ever. And then you need to add a general purpose compression algorithm to further reduce the image size which brings us back to my previous point.

I simply haven't found a single decent compressed CD image format out there (or really, a decent CD image format <full stop>). Such a format should strip the ECC and subchannel data when it's not necessary, compress the data sector with a good general purpose algo and use an audio codec for the audio tracks. It should also have some kind of an index to allow random access without having to decompress everything first.

**Comment by Zapeth** [comment]
Not meaning to dig this up but considering it was recently requested and is currently WIP (https://github.com/libretro/beetle-psx-libretro/issues/219 ), MAME's CHD file format seems to be the most ideal solution for CD-based systems.

General purpose data gets compressed using a combination of LZMA and Deflate algorithms while audio data gets converted to lossless flac codec data, all of which gets stored in "hunks" to make use of the principle of locality.

The resulting converted file is in some cases even smaller than an image file that was compressed with more agressive settings of general-purpose compression algorithms like LZMA2 and RAR5.

Plus the file format is entirely open and the official conversion tool is part of MAME's collection of tools, so its likely to maintained regularily and possibly even improved (as opposed to some closed format like Sony's PBP files).

**Comment by rz5** [comment]
@Zapeth implemented both PBP and CHD file support. I believe that fact warrants closing this issue.

**Comment by DwarfFighterCleric** [comment]
Hey guys do you know about any tutorial on reducing the size of PS1 roms? Just for playing regularly on the computer, I just wanna remove unnecessary XA/STR files to make sizes smaller. What tools should I use?

**Comment by piratesephiroth** [comment]
I think most (if not all) PS1 games use hardcoded offsets for the files so you normally can't simply remove stuff because it would shift everything that comes after it (unless it's at the end of the iso)

**Comment by DwarfFighterCleric** [comment]
I would like to try anyway :) I wonder if there are emulators that are able to overcome this "hardcoded sectors" thing. I downloaded JpsxDec but it requires Java, I'm on linux at the moment, no easy chance of java here. Shit gets complicated :(
Oh, and do you know sites for downloading Rips? (psx games with no music or movies for smaller sizes) These were easier to find a while ago

**Comment by piratesephiroth** [comment]
you should probably consult a romhacking forum then
