### ISSUE TITLE
Space Debris (SCES-02290) does not boot

### ISSUE THREAD

**Issue by daninthemix** [libretro/beetle-psx-libretro#808]
Using either beetle HW or Software, Space Debris does not boot. After the startup anthem, you get a black screen and then nothing. And nothing in the log either. There's no crash, the emulator is still running. It just doesn't make it into the title screen.

**Comment by TheOligopolist** [comment]
You will require the sub channel data (.sbi file) There are a number of PAL games that require this file due to copy protection, in order to run correctly.
You can get these from the redump.org website, the file will need to be named the same as the image and in the same folder, eg:

SPACE_DEBRIS.chd
SPACE_DEBRIS.sbi

**Comment by daninthemix** [comment]
Oh brilliant - thanks for that!
