### ISSUE TITLE
SaGa Frontier (USA) - Black screen when skipping bios

### ISSUE THREAD

**Issue by orbea** [libretro/beetle-psx-libretro#82]
OS: `Slackware64-current`
`RetroArch-1.3.6-x86_64-1_SBo`
`pcsx-rearmed-10ed51a_2016.06.18_master-x86_64-1_git`
`beetle-psx-libretro-2016.08.18_2c2e41d_master-x86_64-1_git`

When starting a redump of `SaGa Frontier (USA)` a black screen will be encountered, the game is not frozen as both sound and input still work. This will occur with both the software and OpenGL renderers, but it will work correctly with `pcsx-rearmed`.

```
md5sum: 95f57b8f33470e6763c0a947b9e1a13f
crc32: 907455ad
```

**Comment by Oggom** [comment]
Are you skipping the BIOS?

**Comment by orbea** [comment]
Yes, that seems to be the issue. It only occurs if the bios is skipped.

**Comment by orbea** [comment]
I have confirmed this still works with `pcsx-rearmed` when no bios is used, so this seems to be a problem with the emulation at least partially.

**Comment by bigboo3000** [comment]
I can confirm that this problem is still present in beetle psx latest version on windows

**Comment by knoxyouout** [comment]
Just updating that I currently experience this issue with the latest Windows release.

**Comment by rz5** [comment]
This may be one of the limitations of this hack.

**Comment by simias** [comment]
I'm not sure if we could really make this better without getting super deep into BIOS hacking. I think the best way to handle these things would be to have a proper HLE BIOS instead of messing with the stock ROM but obviously that's a whole other can of worms.

Alternatively we could also work around it with savestates: create a "generic" savestate before the BIOS starts loading CD data and load that to skip the BIOS intro.

Lastly if we want to keep the current method and fix this issue one would have to figure out what changes in the hardware state between the normal and hacked boot sequence and patch the code to fix it. I suspect something SPU or GPU related.

**Comment by orbea** [comment]
Thanks for the explanation, I don't consider this high priority, but it could be nice to come up with a proper fix in time. :)
