### ISSUE TITLE
Saving state causes graphics mode to glitch

### ISSUE THREAD

**Issue by GregorR** [libretro/beetle-psx-libretro#92]
Saving a state in mednafen_psx causes the graphics mode to momentarily change; I THINK that it's switching away from 3D mode into 2D mode. Testing with Crash Bash, if you save state on the main menu, it will momentarily flicker to the last 2D credits screen before continuing. For typical use this is no big deal, but netplay saves the state every frame, and that's making netplay unusable with this core.

**Comment by GregorR** [comment]
Hm, cancel this for now. I'm getting different issues now... I'll reopen a new report when I've figured out what's actually going on.

**Comment by simias** [comment]
I can confirm that it's how it works currently, creating a savestate forces a sync between the SW and HW framebuffers which means that you'll get one frame of SW displayed before the GL code takes over again. I never bothered bothered changing this because I didn't think it was really noticeable, but obviously I underestimated your eyesight!

**Comment by simias** [comment]
Should be fixed now.

**Comment by GregorR** [comment]
While your praise of my eyesight is appreciated, I only originally noticed it because it was VERY strange under Netplay, which savestates every frame, and so looked like it was stuck in the wrong mode. Only when I knew what to look for could I see it in normal execution :)

Thanks for the fix!
